((root,factory)=>{const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.XiaoluAchievementCore=api;})(typeof globalThis==="object"?globalThis:window,()=>{
  "use strict";
  const KEY="xiaoluXiaogAchievementsV2",SCHEMA_VERSION=1;
  const read=(storage,key,fallback)=>{try{const value=JSON.parse(storage?.getItem(key)||"null");return value??fallback}catch{return fallback}};
  const array=value=>Array.isArray(value)?value:[],object=value=>value&&typeof value==="object"&&!Array.isArray(value)?value:{};
  const oldest=list=>array(list).map(x=>x?.date||x?.createdAt||x?.completedAt).filter(Boolean).sort()[0]||null;
  const firstAt=(list,predicate=()=>true)=>oldest(array(list).filter(predicate));
  const make=(id,icon,name,description,category,unlocked,inferredAt=null)=>({id,icon,name,description,category,unlocked:Boolean(unlocked),inferredAt});
  function evaluate(storage=globalThis.localStorage,now=new Date()){
    const arcade=object(read(storage,"xiaoluXiaogArcadeV1",{})),quizHistory=array(read(storage,"xiaoluQuizBattleHistoryV1",[])),quiz=object(read(storage,"xiaoluQuizStatsV15",{})),transport=object(read(storage,"xiaoluXiaogTransportV1",{}));
    const wishes=array(read(storage,"xiaoluXiaogWishlistV1",[])),travel=array(read(storage,"xiaoluXiaogTravelV1",{}).records),exercise=array(read(storage,"xiaoluXiaogExerciseV1",{}).records),memories=array(read(storage,"xiaoluXiaogTimelineV1",{}).memories),notes=array(read(storage,"xiaoluXiaogNotesV1",{}).notes),study=object(read(storage,"xiaoluXiaogVocabularyV2",{}));
    const transportCatalog={bus:"urban",subway:"urban","light-rail":"urban",taxi:"urban",bicycle:"urban","e-bike":"urban",train:"railway","hard-seat":"railway","hard-sleeper":"railway","soft-sleeper":"railway","high-speed-rail":"railway",emu:"railway",intercity:"railway",coach:"road","self-drive":"road",motorcycle:"road",plane:"air",ferry:"water","tour-boat":"water",cruise:"water",maglev:"special",tram:"special","cable-car":"special",ropeway:"special","sightseeing-train":"special"};
    array(transport.custom).forEach(item=>{if(item?.id)transportCatalog[item.id]=item.category||"future"});
    const unlockedTransportIds=Object.keys(transportCatalog).filter(id=>["experienced","special"].includes(transport.entries?.[id]?.state)),unlockedTransport=new Set(unlockedTransportIds),transportTotal=Object.keys(transportCatalog).length;
    const plays={lyrics:0,timer:0,sync:0,memory:0,world:0,province:0,...object(arcade.plays)},totalPlays=Object.values(plays).reduce((sum,value)=>sum+(Number(value)||0),0)+Math.max(Number(quiz.plays)||0,quizHistory.length);
    const memory=object(arcade.memoryBest),timer=object(arcade.timerSoloBest),lyrics=object(arcade.lyricsBest),province=object(arcade.provinceBest),world=object(arcade.worldBest);
    const memoryGreat=Object.entries(memory).some(([level,value])=>value&&Number.isFinite(value.moves)&&value.moves<=({easy:10,normal:18,hard:26}[level]||16));
    const nearMiss=(Number.isFinite(timer.average)&&timer.average>.30&&timer.average<=.35)||arcade.syncBest===7||(world.score>=28&&world.score<30)||province.ten===7||(province.twenty>=14&&province.twenty<16);
    const completedWishes=wishes.filter(x=>x?.status==="done"),visited=travel.filter(x=>["visited","special"].includes(x?.status)),completedExercise=exercise.filter(x=>x?.status==="completed"&&x?.type!=="休息"),restDays=exercise.filter(x=>x?.status==="rest"||x?.type==="休息");
    const studyHistory=Object.values(object(study.books)).flatMap(book=>array(book?.history)),dailyFifty=studyHistory.filter(x=>x?.mode==="daily"&&Number(x.words)>=50);
    const definitions=[
      make("first-play","🎮","初次开黑","完成任意一局游戏。","游戏",totalPlays>0,oldest([...array(arcade.syncHistory),...array(arcade.timerHistory),...array(arcade.lyricsHistory),...quizHistory])),
      make("science-pride","🧠","理科生尊严","知识擂台拿到 8 分或更多。","游戏",(quiz.bestScore||0)>=8||quizHistory.some(x=>x.xiaoluScore>=8)),make("xiaolu-wins","🌟","小路赢啦","小路第一次在双人知识擂台战胜小G。","游戏",quizHistory.some(x=>x.result==="小路胜"),firstAt(quizHistory,x=>x.result==="小路胜")),make("ai-oops","🤖","人机翻车现场","小G在知识擂台至少答错一道题。","游戏",quizHistory.some(x=>x.xiaogScore<10),firstAt(quizHistory,x=>x.xiaogScore<10)),make("streak-engine","🔥","连胜发动机","知识问答连续答对 5 题。","游戏",(quiz.bestStreak||0)>=5),make("in-sync","💞","心有灵犀","默契挑战一局匹配 8 题或更多。","游戏",array(arcade.syncHistory).some(x=>x.score>=8),firstAt(arcade.syncHistory,x=>x.score>=8)),make("do-we-know","😹","我们真的认识吗","默契只有 2 格也没关系，笑着玩完最重要。","游戏",array(arcade.syncHistory).some(x=>x.score<=2),firstAt(arcade.syncHistory,x=>x.score<=2)),make("world-traveler","🌍","世界旅行家","世界猜猜猜拿到 30 分或更多。","游戏",(world.score||0)>=30),make("china-map","🗺️","中国地图装进脑子","猜省份正确率达到 80%。","游戏",(province.ten||0)>=8||(province.twenty||0)>=16),make("memory-master","🧩","记忆大师","用很少的步数完成一次记忆翻牌。","游戏",memoryGreat),make("human-stopwatch","⏱️","人体秒表","读秒挑战平均误差不超过 0.30 秒。","游戏",Number.isFinite(timer.average)&&timer.average<=.30,firstAt(arcade.timerHistory,x=>x.average<=.30)),make("perfect-tick","⚡","分秒不差","读秒挑战单次误差不超过 0.10 秒。","游戏",Number.isFinite(timer.single)&&timer.single<=.10),make("song-library","🎵","中华小曲库","猜歌词一局答对 4 题或更多。","游戏",(lyrics.xiaolu||0)>=4||(lyrics.xiaog||0)>=4,firstAt(arcade.lyricsHistory,x=>x.xiaolu>=4||x.xiaog>=4)),make("revenge","⚔️","复仇成功","在错题复仇中重新答对一道题。","游戏",(quiz.revengeWins||0)>0),make("so-close","🌙","差一点点","用特别接近的成绩擦过更高档位。","游戏",nearMiss),make("regular","🏠","小家常客","累计完成 10 局游戏。","游戏",totalPlays>=10),
      make("transport-urban","🚇","城市探索者","体验地铁或轻轨。","足迹",unlockedTransport.has("subway")||unlockedTransport.has("light-rail"),transport.achievementDates?.["transport-urban"]),make("transport-rail","🚆","铁路旅行者","体验三种铁路交通。","足迹",unlockedTransportIds.filter(id=>transportCatalog[id]==="railway").length>=3,transport.achievementDates?.["transport-rail"]),make("transport-air","✈️","第一次飞向天空","点亮客机。","足迹",unlockedTransport.has("plane"),transport.achievementDates?.["transport-air"]),make("transport-water","⛴️","水上旅行者","体验任意一种水上交通。","足迹",unlockedTransportIds.some(id=>transportCatalog[id]==="water"),transport.achievementDates?.["transport-water"]),make("transport-collector","🎒","交通收藏家","解锁十种交通工具。","足迹",unlockedTransportIds.length>=10,transport.achievementDates?.["transport-collector"]),make("transport-master","🏆","交通大师","交通图鉴完成度达到 80%。","足迹",transportTotal>0&&unlockedTransportIds.length/transportTotal>=.8,transport.achievementDates?.["transport-master"]),
      make("wish-first","🌱","第一颗愿望种子","写下第一条愿望。","生活",wishes.length>=1,oldest(wishes)),make("wish-first-done","✨","愿望变成回忆","完成第一条愿望。","生活",completedWishes.length>=1,oldest(completedWishes)),make("footprint-first","🧭","地图的第一枚脚印","保存第一条足迹。","生活",travel.length>=1,oldest(travel)),make("footprint-five","🗺️","一起走过五处风景","记录五个已去过的地点。","生活",visited.length>=5,oldest(visited.slice(0,5))),make("exercise-first","🏃","第一次一起运动","完成第一条运动记录。","成长",completedExercise.length>=1,oldest(completedExercise)),make("exercise-five","🌿","身体记住了五次努力","累计完成 5 次运动。","成长",completedExercise.length>=5,oldest(completedExercise.slice(0,5))),make("exercise-ten","💪","十次温柔的坚持","累计完成 10 次运动。","成长",completedExercise.length>=10,oldest(completedExercise.slice(0,10))),make("exercise-rest","☁️","安心休息也是计划","第一次记录休息日。","成长",restDays.length>=1,oldest(restDays)),make("timeline-first","📸","第一帧回忆","保存第一条回忆。","生活",memories.length>=1,oldest(memories)),make("timeline-ten","❤️","十个舍不得忘记的日子","保存第 10 条回忆。","生活",memories.length>=10,oldest(memories.slice(0,10))),make("note-first","📝","第一张小纸条","保存第一条笔记。","成长",notes.length>=1,oldest(notes)),make("note-ten","📚","十页慢慢长大的文字","保存第 10 条笔记。","成长",notes.length>=10,oldest(notes.slice(0,10))),make("study-daily-fifty","📖","今天的五十词","第一次完成每日 50 词。","成长",dailyFifty.length>=1,oldest(dailyFifty))
    ];
    const achievementRaw=storage?.getItem(KEY);let achievementBroken=false,rawState={};if(achievementRaw!==null&&achievementRaw!==undefined){try{rawState=object(JSON.parse(achievementRaw))}catch{achievementBroken=true}}
    const futureSchema=Number(rawState.schemaVersion)>SCHEMA_VERSION,unlockedState=object(rawState.unlocked),next={...rawState,schemaVersion:futureSchema?rawState.schemaVersion:SCHEMA_VERSION,unlocked:{...unlockedState}};let changed=!futureSchema&&!achievementBroken&&rawState.schemaVersion!==SCHEMA_VERSION;
    definitions.filter(x=>x.unlocked).forEach(item=>{if(!next.unlocked[item.id]?.unlockedAt&&!futureSchema){next.unlocked[item.id]={unlockedAt:item.inferredAt||now.toISOString()};changed=true}item.unlockedAt=next.unlocked[item.id]?.unlockedAt||item.inferredAt});
    definitions.filter(x=>!x.unlocked).forEach(item=>{if(next.unlocked[item.id]?.unlockedAt){item.unlocked=true;item.unlockedAt=next.unlocked[item.id].unlockedAt}});
    if(changed&&!achievementBroken)try{storage?.setItem(KEY,JSON.stringify(next))}catch{}
    const unlocked=definitions.filter(x=>x.unlocked),latest=[...unlocked].sort((a,b)=>String(b.unlockedAt||b.inferredAt||"").localeCompare(String(a.unlockedAt||a.inferredAt||"")))[0]||null;
    return {definitions,unlocked,latest,state:next};
  }
  return {KEY,SCHEMA_VERSION,evaluate};
});
