(() => {
 const $=id=>document.getElementById(id),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},norm=s=>s.trim().toLowerCase().replace(/[\s，。！？；：、,.!?;:·《》“”'"（）()\-]/g,"");
 let mode,questions,index,layer,score,correct,totalClues,firstClue,locked;
 document.querySelectorAll("[data-clue-mode]").forEach(b=>b.onclick=()=>start(b.dataset.clueMode));
 function start(m){mode=m;const pool=m==="mixed"?[...ClueData.people,...ClueData.places,...ClueData.things]:ClueData[m];questions=shuffle(pool).slice(0,10);index=score=correct=totalClues=firstClue=0;$("clue-setup").hidden=true;$("clue-game").hidden=false;show()}
 function show(){layer=1;locked=false;$("clue-input").value="";$("clue-input").disabled=false;$("clue-feedback").hidden=true;$("clue-title").textContent=`🔎 ${{people:"人物",places:"地点",things:"事物",mixed:"混合"}[mode]}`;$("clue-round").textContent=`题目 ${index+1} / 10`;render();$("clue-input").focus()}
 function render(){const q=questions[index];$("clue-score").textContent=`${score} / 40`;$("clue-correct").textContent=correct;$("clue-layer").textContent=`${layer} / 4`;$("clue-list-open").innerHTML=q.clues.slice(0,layer).map((x,i)=>`<div><span>线索 ${i+1}</span><p>${x}</p></div>`).join("");$("clue-more").disabled=layer>=4;$("clue-giveup").hidden=layer<4}
 $("clue-more").onclick=()=>{if(layer<4){layer++;render()}};
 $("clue-form").onsubmit=e=>{e.preventDefault();if(locked)return;const q=questions[index],accepted=[q.answer,...q.aliases].map(norm),ok=accepted.includes(norm($("clue-input").value));if(ok){const pts=5-layer;score+=pts;correct++;totalClues+=layer;if(layer===1)firstClue++;finishQuestion(true,`答对了！获得 ${pts} 分。`)}else if(layer<4){const old=$("clue-input").value;layer++;render();feedback(false,`“${old}”不对，再给你一条线索。`);$("clue-input").select()}else finishQuestion(false,`正确答案是：${q.answer}`)};
 $("clue-giveup").onclick=()=>finishQuestion(false,`正确答案是：${questions[index].answer}`);
 function feedback(ok,text){const f=$("clue-feedback");f.className=`feedback ${ok?"correct-feedback":"wrong-feedback"}`;f.innerHTML=`<strong>${text}</strong>`;f.hidden=false}
 function finishQuestion(ok,text){locked=true;$("clue-input").disabled=true;if(!ok)totalClues+=4;feedback(ok,text);$("clue-feedback").innerHTML+=`<button class="primary-button next-button" id="clue-next">${index===9?"查看结算":"下一题"}</button>`;$("clue-next").onclick=()=>{index++;index<10?show():finish()};render()}
 function finish(){const avg=(totalClues/10).toFixed(1);$("clue-game").hidden=true;$("clue-result").innerHTML=`<div class="result-emoji">🔍</div><p class="eyebrow">CASE CLOSED</p><h2>线索挑战完成</h2><p class="score-line"><strong>${score}</strong><span>/ 40 分</span></p><div class="result-grid"><div><small>猜对数量</small><strong>${correct}</strong></div><div><small>平均线索数</small><strong>${avg}</strong></div><div><small>首条猜中</small><strong>${firstClue}</strong></div><div><small>总题数</small><strong>10</strong></div></div><div class="actions result-actions"><button class="primary-button" onclick="location.reload()">再玩一局</button><a class="text-button" href="./game-hall.html">返回游戏厅</a></div>`;$("clue-result").hidden=false}
})();
