(() => {
  "use strict";
  const store=window.XiaoluExerciseStore,loaded=store.load();let state=loaded.state,locked=Boolean(loaded.locked),range="week";
  const $=s=>document.querySelector(s),dialog=$("#record-dialog"),form=$("#record-form"),nowDate=new Date(),today=new Date(nowDate.getTime()-nowDate.getTimezoneOffset()*60000).toISOString().slice(0,10);
  const localDate=value=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric"}).format(new Date(value+"T00:00:00"));
  const option=(value,label=value)=>{const el=document.createElement("option");el.value=value;el.textContent=label;return el;};
  function memories(){try{const rows=JSON.parse(localStorage.getItem("xiaoluXiaogTimelineV1")||"{}").memories;return Array.isArray(rows)?rows:[]}catch{return[]}}
  store.TYPES.forEach(type=>{$("#record-type").append(option(type));$("#type-filter").append(option(type));});$("#record-date").value=today;$("#today-label").textContent=localDate(today);if(loaded.warning){$("#storage-warning").hidden=false;$("#storage-warning").textContent=loaded.warning;}
  function persist(){if(locked)return false;const ok=store.save(state);if(!ok){$("#storage-warning").hidden=false;$("#storage-warning").textContent="浏览器存储空间不足，本次修改未保存。";}return ok;}
  let toastTimer;function notify(message){let toast=document.querySelector(".save-toast");if(!toast){toast=document.createElement("div");toast.className="save-toast";toast.setAttribute("role","status");document.body.append(toast)}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},2200)}
  function button(label,action,cls=""){const el=document.createElement("button");el.type="button";el.textContent=label;el.dataset.action=action;el.className=cls;return el;}
  function empty(icon,text){const el=document.createElement("div");el.className="empty-state";const i=document.createElement("span"),p=document.createElement("p");i.textContent=icon;p.textContent=text;el.append(i,p);return el;}
  function linked(item){return memories().filter(x=>x?.source?.module==="exercise"&&String(x.source.itemId)===item.id)}
  function card(item){const el=document.createElement("article");el.className="record-card";el.dataset.id=item.id;const top=document.createElement("div"),h=document.createElement("h3"),badge=document.createElement("span");top.className="record-top";h.textContent=item.type==="休息"?(item.action||"休息日"):(item.action||item.type);badge.className="tag";badge.textContent=item.status==="completed"?"已完成":item.status==="planned"?"计划中":"安心休息";top.append(h,badge);el.append(top);const meta=document.createElement("div");meta.className="record-meta";[localDate(item.date),item.type,item.sets?item.sets+" 组":"",item.reps?item.reps+" 次":"",item.durationMinutes?item.durationMinutes+" 分钟":"",item.feeling].filter(Boolean).forEach(x=>{const s=document.createElement("span");s.textContent=x;meta.append(s)});el.append(meta);if(item.note){const p=document.createElement("p");p.textContent=item.note;el.append(p)}const actions=document.createElement("div");actions.className="record-actions";const found=linked(item)[0],memoryButton=button(found?"查看回忆":"写成回忆",found?"view-memory":"memory");if(found)memoryButton.dataset.memoryId=found.id;actions.append(memoryButton,button("编辑","edit"),button("删除","delete","delete-action"));el.append(actions);return el;}
  function periodStart(){const d=new Date(today+"T00:00:00");if(range==="month")return today.slice(0,7)+"-01";const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10);}
  function renderStats(){const rows=state.records.filter(x=>x.date>=periodStart()&&x.date<=today&&(x.status==="completed"||x.status==="rest"));const training=rows.filter(x=>x.status==="completed"&&x.type!=="休息"),rests=rows.filter(x=>x.status==="rest"||x.type==="休息");$("#range-label").textContent=range==="week"?"本周训练":"本月训练";$("#training-count").textContent=training.length+" 次";$("#duration-total").textContent=training.reduce((n,x)=>n+x.durationMinutes,0)+" 分钟";$("#rest-count").textContent=new Set(rests.map(x=>x.date)).size+" 天";const counts=Object.fromEntries(store.TYPES.map(x=>[x,rows.filter(r=>r.type===x).length]));const max=Math.max(1,...Object.values(counts)),box=$("#type-bars");box.replaceChildren();store.TYPES.forEach(type=>{const row=document.createElement("div"),label=document.createElement("span"),track=document.createElement("div"),bar=document.createElement("i"),count=document.createElement("b");row.className="type-bar";label.textContent=type;bar.style.width=counts[type]/max*100+"%";track.append(bar);count.textContent=counts[type];row.append(label,track,count);box.append(row)});}
  function render(){renderStats();const todayRows=state.records.filter(x=>x.date===today).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));$("#today-list").replaceChildren(...(todayRows.length?todayRows.map(card):[empty("🌿","今天还没有记录，休息也可以被好好记下。")]));const q=$("#record-search").value.trim().toLowerCase(),type=$("#type-filter").value,status=$("#status-filter").value;const rows=state.records.filter(x=>x.date!==today&&(!type||x.type===type)&&(!status||x.status===status)&&(!q||(x.action+" "+x.note+" "+x.feeling).toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));$("#history-list").replaceChildren(...(rows.length?rows.map(card):[empty("🗓️","暂无符合条件的历史记录。")]));}
  function open(item){form.reset();$("#record-id").value=item?.id||"";$("#record-date").value=item?.date||today;$("#record-type").value=item?.type||"臀腿";$("#record-action").value=item?.action||"";$("#record-sets").value=item?.sets||"";$("#record-reps").value=item?.reps||"";$("#record-duration").value=item?.durationMinutes||"";$("#record-status").value=item?.status||"completed";$("#record-feeling").value=item?.feeling||"";$("#record-note").value=item?.note||"";$("#dialog-title").textContent=item?"编辑训练记录":"记录训练";dialog.showModal();}
  function highlight(id){requestAnimationFrame(()=>{const card=document.querySelector('.record-card[data-id="'+CSS.escape(id)+'"]');if(card){card.classList.add("source-highlight");card.scrollIntoView({block:"center"});}})}
  $("#add-record").addEventListener("click",()=>open());document.querySelectorAll(".dialog-close,.cancel-button").forEach(x=>x.addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});$("#record-type").addEventListener("change",e=>{if(e.target.value==="休息")$("#record-status").value="rest";});
  form.addEventListener("submit",e=>{e.preventDefault();if(locked)return;const now=new Date().toISOString(),raw={id:$("#record-id").value,date:$("#record-date").value,type:$("#record-type").value,action:$("#record-action").value,sets:$("#record-sets").value,reps:$("#record-reps").value,durationMinutes:$("#record-duration").value,status:$("#record-status").value,feeling:$("#record-feeling").value,note:$("#record-note").value,updatedAt:now};const current=state.records.find(x=>x.id===raw.id),next=store.normalizeRecord({...current,...raw,createdAt:current?.createdAt||now});if(current)Object.assign(current,next);else state.records.push(next);if(persist()){dialog.close();render();highlight(next.id);notify(current?"运动记录已更新":"运动记录已保存");}});
  document.querySelector(".life-shell").addEventListener("click",e=>{const rangeButton=e.target.closest("[data-range]");if(rangeButton){range=rangeButton.dataset.range;document.querySelectorAll("[data-range]").forEach(x=>x.setAttribute("aria-pressed",String(x===rangeButton)));render();return}const action=e.target.closest("[data-action]");if(!action)return;const item=state.records.find(x=>x.id===action.closest(".record-card")?.dataset.id);if(!item)return;if(action.dataset.action==="edit")open(item);else if(action.dataset.action==="memory"){const params=new URLSearchParams({source:"exercise",sourceId:item.id,sourceLabel:item.action||item.type,title:item.action||item.type,body:item.note||"",date:item.date});location.href="./timeline.html?"+params}else if(action.dataset.action==="view-memory")location.href="./timeline.html?memoryId="+encodeURIComponent(action.dataset.memoryId);else if(action.dataset.action==="delete"&&confirm("确定删除这条运动记录吗？不会删除已关联的回忆。")){state.records=state.records.filter(x=>x.id!==item.id);if(persist()){render();notify("运动记录已删除")}}});
  ["record-search","type-filter","status-filter"].forEach(id=>$("#"+id).addEventListener(id==="record-search"?"input":"change",render));render();const target=new URLSearchParams(location.search).get("recordId");if(target)highlight(target);
})();
