((root,factory)=>{const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.XiaoluGiftsStore=api;})(typeof globalThis==="object"?globalThis:window,()=>{
  "use strict";
  const KEY="xiaoluXiaogGiftsV1",SCHEMA_VERSION=1,TYPES=["文件礼物","纪念小物","数字礼物","惊喜","其他"];
  const text=(value,max=1000)=>(typeof value==="string"||typeof value==="number"?String(value).trim().slice(0,max):"");
  const id=value=>(typeof value==="string"||typeof value==="number"?text(value,100):"")||globalThis.crypto?.randomUUID?.()||`gift-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const date=value=>{const raw=String(value||""),parsed=new Date(`${raw}T00:00:00Z`);return /^\d{4}-\d{2}-\d{2}$/.test(raw)&&!Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===raw?raw:new Date().toISOString().slice(0,10)};
  const tags=value=>(Array.isArray(value)?value.filter(x=>typeof x==="string"):typeof value==="string"?value.split(/[，,]/):[]).map(x=>text(x,30)).filter(Boolean).filter((x,i,all)=>all.indexOf(x)===i).slice(0,20);
  const stringIds=value=>Array.isArray(value)?value.filter(x=>typeof x==="string"||typeof x==="number").map(x=>text(x,100)).filter(Boolean).filter((x,i,all)=>all.indexOf(x)===i).slice(0,50):[];
  function normalizeGift(input={}){return {id:id(input.id),date:date(input.date),name:text(input.name,120),type:TYPES.includes(input.type)?input.type:"其他",giver:text(input.giver,120),description:text(input.description,3000),imageRef:/^https?:\/\//i.test(text(input.imageRef,500))?text(input.imageRef,500):"",tags:tags(input.tags),favorite:Boolean(input.favorite),links:{memoryIds:stringIds(input.links?.memoryIds)},createdAt:text(input.createdAt,40)||new Date().toISOString(),updatedAt:text(input.updatedAt,40)||new Date().toISOString()}}
  function normalizeState(input){const source=input&&typeof input==="object"&&!Array.isArray(input)?input:{},seen=new Set();return {schemaVersion:SCHEMA_VERSION,gifts:Array.isArray(source.gifts)?source.gifts.filter(x=>x&&typeof x==="object").map(normalizeGift).filter(x=>x.name&&!seen.has(x.id)&&seen.add(x.id)):[]}}
  function load(storage=globalThis.localStorage){const raw=storage?.getItem(KEY);if(raw==null)return {state:normalizeState(),warning:""};try{const parsed=JSON.parse(raw);if(Number(parsed?.schemaVersion)>SCHEMA_VERSION)return {state:normalizeState(parsed),warning:"礼物数据来自更新版本，当前页面仅供查看。",locked:true};return {state:normalizeState(parsed),warning:""}}catch{return {state:normalizeState(),warning:"礼物数据格式异常，已暂停覆盖原始数据。",locked:true}}}
  function save(state,storage=globalThis.localStorage){try{storage.setItem(KEY,JSON.stringify(normalizeState(state)));return true}catch{return false}}
  function linkMemory(state,giftId,memoryId){const next=normalizeState(state),gift=next.gifts.find(item=>item.id===text(giftId,100)),memory=text(memoryId,100);if(gift&&memory&&!gift.links.memoryIds.includes(memory)){gift.links.memoryIds.unshift(memory);gift.updatedAt=new Date().toISOString()}return next}
  function unlinkMemory(state,memoryId){const next=normalizeState(state),memory=text(memoryId,100);next.gifts.forEach(gift=>{gift.links.memoryIds=gift.links.memoryIds.filter(id=>id!==memory)});return next}
  return {KEY,SCHEMA_VERSION,TYPES,normalizeGift,normalizeState,load,save,linkMemory,unlinkMemory};
});
