(() => {
  "use strict";
  const store=window.XiaoluGiftsStore,loaded=store.load();let state=loaded.state,locked=Boolean(loaded.locked),view="all";
  const $=selector=>document.querySelector(selector),dialog=$("#gift-dialog"),form=$("#gift-form"),nowDate=new Date(),today=new Date(nowDate.getTime()-nowDate.getTimezoneOffset()*60000).toISOString().slice(0,10);
  if(loaded.warning){$("#storage-warning").hidden=false;$("#storage-warning").textContent=loaded.warning;}
  store.TYPES.forEach(type=>[$("#type-filter"),$("#gift-type")].forEach(select=>select.append(Object.assign(document.createElement("option"),{value:type,textContent:type}))));
  function persist(){if(locked)return false;const ok=store.save(state);if(!ok){$("#storage-warning").hidden=false;$("#storage-warning").textContent="浏览器存储空间不足，本次修改未保存。";}return ok;}
  let toastTimer;function notify(message){let toast=document.querySelector(".save-toast");if(!toast){toast=document.createElement("div");toast.className="save-toast";toast.setAttribute("role","status");document.body.append(toast)}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},2200)}
  function button(label,action,cls=""){const el=document.createElement("button");el.type="button";el.textContent=label;el.dataset.action=action;el.className=cls;return el;}
  function linkedMemory(gift){const memories=window.XiaoluTimelineStore?.load().state.memories||[];return memories.find(memory=>memory.source.module==="gift"&&memory.source.itemId===gift.id||memory.links.giftIds?.includes(gift.id))}
  function updateTags(){const select=$("#tag-filter"),selected=select.value,tags=[...new Set(state.gifts.flatMap(gift=>gift.tags))].sort((a,b)=>a.localeCompare(b,"zh-CN"));select.replaceChildren(Object.assign(document.createElement("option"),{value:"",textContent:"全部标签"}),...tags.map(value=>Object.assign(document.createElement("option"),{value,textContent:"# "+value})));select.value=tags.includes(selected)?selected:""}
  function card(item){const el=document.createElement("article");el.className="record-card gift-card"+(item.favorite?" is-favorite":"");el.dataset.id=item.id;const top=document.createElement("div"),title=document.createElement("h3"),marks=document.createElement("div");top.className="record-top";title.textContent=item.name;marks.className="memory-marks";marks.append(Object.assign(document.createElement("span"),{textContent:`🎀 ${item.type}`}));if(item.favorite)marks.append(Object.assign(document.createElement("span"),{textContent:"⭐ 收藏"}));top.append(title,marks);el.append(top);const meta=document.createElement("div");meta.className="record-meta";[item.date,item.giver?"来自 "+item.giver:""].filter(Boolean).forEach(value=>meta.append(Object.assign(document.createElement("span"),{textContent:value})));el.append(meta);if(item.description){const description=document.createElement("p");description.textContent=item.description;el.append(description)}if(item.tags.length){const tags=document.createElement("div");tags.className="tag-row";item.tags.forEach(value=>{const tag=document.createElement("button");tag.type="button";tag.className="tag";tag.dataset.tag=value;tag.textContent="# "+value;tags.append(tag)});el.append(tags)}if(item.imageRef){const image=document.createElement("a");image.className="memory-image-link";image.href=item.imageRef;image.target="_blank";image.rel="noopener noreferrer";image.textContent="查看图片引用 ↗";el.append(image)}const actions=document.createElement("div");actions.className="record-actions";const linked=linkedMemory(item),memory=document.createElement("a");if(linked){memory.href="./timeline.html?memoryId="+encodeURIComponent(linked.id);memory.textContent="查看关联回忆"}else{const params=new URLSearchParams({source:"gift",sourceId:item.id,sourceLabel:item.name,title:item.name,body:item.description,date:item.date,imageRef:item.imageRef,tags:item.tags.join("，")});memory.href="./timeline.html?"+params;memory.textContent="写成回忆"}actions.append(memory,button(item.favorite?"取消收藏":"收藏","favorite"),button("编辑","edit"),button("删除","delete","delete-action"));el.append(actions);return el}
  function empty(){const el=document.createElement("div");el.className="empty-state";el.append(Object.assign(document.createElement("span"),{textContent:"🎁"}),Object.assign(document.createElement("p"),{textContent:view==="favorite"?"还没有收藏的礼物。":"礼物盒还是空的，放入第一份想珍藏的礼物吧。"}));return el}
  function render(){updateTags();const q=$("#gift-search").value.trim().toLowerCase(),type=$("#type-filter").value,tag=$("#tag-filter").value;const rows=state.gifts.filter(gift=>(view==="all"||gift.favorite)&&(!type||gift.type===type)&&(!tag||gift.tags.includes(tag))&&(!q||(gift.name+" "+gift.description+" "+gift.giver+" "+gift.tags.join(" ")).toLowerCase().includes(q))).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));$("#result-summary").textContent=`共 ${rows.length} 份礼物${state.gifts.filter(gift=>gift.favorite).length?` · 已收藏 ${state.gifts.filter(gift=>gift.favorite).length} 份`:""}`;$("#gift-list").replaceChildren(...(rows.length?rows.map(card):[empty()]))}
  function open(item=null){form.reset();$("#gift-id").value=item?.id||"";$("#gift-date").value=item?.date||today;$("#gift-type").value=item?.type||"纪念小物";$("#gift-name").value=item?.name||"";$("#gift-giver").value=item?.giver||"";$("#gift-description").value=item?.description||"";$("#gift-tags").value=(item?.tags||[]).join("，");$("#gift-image").value=item?.imageRef||"";$("#gift-favorite").checked=Boolean(item?.favorite);$("#dialog-title").textContent=item?"编辑这份礼物":"放入一份礼物";dialog.showModal()}
  function highlight(id){requestAnimationFrame(()=>{const found=document.querySelector('.record-card[data-id="'+CSS.escape(id)+'"]');if(found){found.classList.add("source-highlight");found.scrollIntoView({block:"center"})}})}
  $("#add-gift").addEventListener("click",()=>open());document.querySelectorAll(".dialog-close,.cancel-button").forEach(control=>control.addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});
  form.addEventListener("submit",event=>{event.preventDefault();if(locked)return;const now=new Date().toISOString(),current=state.gifts.find(gift=>gift.id===$("#gift-id").value),next=store.normalizeGift({...current,id:$("#gift-id").value,date:$("#gift-date").value,name:$("#gift-name").value,type:$("#gift-type").value,giver:$("#gift-giver").value,description:$("#gift-description").value,tags:$("#gift-tags").value,imageRef:$("#gift-image").value,favorite:$("#gift-favorite").checked,createdAt:current?.createdAt||now,updatedAt:now});if(current)Object.assign(current,next);else state.gifts.push(next);if(persist()){dialog.close();render();highlight(next.id);notify(current?"礼物已更新":"礼物已放进礼物盒")}});
  $("#gift-list").addEventListener("click",event=>{const tag=event.target.closest("[data-tag]");if(tag){$("#tag-filter").value=tag.dataset.tag;render();return}const action=event.target.closest("[data-action]");if(!action)return;const item=state.gifts.find(gift=>gift.id===action.closest(".record-card")?.dataset.id);if(!item)return;if(action.dataset.action==="edit")open(item);else if(action.dataset.action==="favorite"){item.favorite=!item.favorite;item.updatedAt=new Date().toISOString();if(persist()){render();notify(item.favorite?"礼物已收藏":"已取消收藏")}}else if(action.dataset.action==="delete"&&confirm("确定从礼物盒删除这份礼物吗？已关联的回忆不会被删除。")){state.gifts=state.gifts.filter(gift=>gift.id!==item.id);if(persist()){render();notify("礼物已删除")}}});
  document.querySelectorAll("[data-gift-filter]").forEach(control=>control.addEventListener("click",()=>{view=control.dataset.giftFilter;document.querySelectorAll("[data-gift-filter]").forEach(button=>{const active=button===control;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});render()}));$("#gift-search").addEventListener("input",render);$("#type-filter").addEventListener("change",render);$("#tag-filter").addEventListener("change",render);
  render();const giftId=new URLSearchParams(location.search).get("giftId");if(giftId)highlight(giftId);
})();
