(() => {
 const $=id=>document.getElementById(id), shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const BOOKS=["红楼梦","西游记","三国演义","水浒传"];
 let mode,classicsMode,items,index=0,correct=0,wrong=0,locked=false,pairs=[],selectedAuthor=null,bookStats={};
 const norm=s=>s.trim().replace(/[，。！？；：、,.!?;:\s]/g,"");
 document.querySelectorAll("[data-lit-mode]").forEach(b=>b.onclick=()=>{if(b.dataset.litMode==="classics"){$("lit-setup").hidden=true;$("classics-setup").hidden=false}else start(b.dataset.litMode)});
 document.querySelectorAll("[data-classics-mode]").forEach(b=>b.onclick=()=>startClassics(b.dataset.classicsMode));
 function startClassics(chosen){classicsMode=chosen;bookStats=Object.fromEntries(BOOKS.map(book=>[book,{correct:0,total:0}]));if(chosen==="综合挑战"){const pools=Object.fromEntries(BOOKS.map(book=>[book,shuffle(LiteratureData.classics.filter(q=>q.book===book))]));items=BOOKS.flatMap(book=>pools[book].splice(0,2));items=shuffle(items.concat(shuffle(BOOKS.flatMap(book=>pools[book])).slice(0,2)))}else items=shuffle(LiteratureData.classics.filter(q=>q.book===chosen)).slice(0,10);start("classics",true)}
 function start(m,prepared=false){mode=m;$("lit-setup").hidden=true;$("classics-setup").hidden=true;$("lit-game").hidden=false;if(m==="classics"&&!prepared)items=shuffle(LiteratureData.classics).slice(0,10);if(m==="poetry")items=shuffle(LiteratureData.poetry).slice(0,10);index=correct=wrong=0;m==="matching"?showMatching():showQuestion()}
 function stats(){$("lit-stats").innerHTML=`<div class="stat-item"><span>正确</span><strong>${correct}</strong></div><div class="stat-item"><span>错误</span><strong>${wrong}</strong></div><div class="stat-item"><span>得分</span><strong>${correct*10}</strong></div>`}
 function showQuestion(){locked=false;$("lit-feedback").hidden=true;$("lit-title").textContent=mode==="classics"?(classicsMode==="综合挑战"?"🏮 四大名著 · 综合挑战":`🏮 《${classicsMode}》专项挑战`):"🪶 诗词接龙";$("lit-round").textContent=`题目 ${index+1} / 10`;$("lit-progress").style.width=`${index*10}%`;stats();const q=items[index];if(mode==="classics"){$("lit-content").innerHTML=`<h2 class="challenge-question">${q.q}</h2><div class="arcade-options">${shuffle(q.o).map(x=>`<button class="arcade-option" data-answer="${x}">${x}</button>`).join("")}</div>`;document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>answerChoice(b,q))}else{const reverse=Math.random()<.5, prompt=reverse?q.after:q.before,answer=reverse?q.before:q.after;$("lit-content").innerHTML=`<div class="poetry-prompt"><small>${reverse?"请填写上一句":"请填写下一句"}</small><strong>${prompt}</strong></div><form id="poetry-form" class="open-answer"><label class="input-label" for="poetry-input">你的接句</label><input id="poetry-input" autocomplete="off" maxlength="30" required><button class="primary-button" type="submit">提交答案</button></form>`;$("poetry-form").onsubmit=e=>{e.preventDefault();if(locked)return;const ok=norm($("poetry-input").value)===norm(answer);finishAnswer(ok,`正确答案：${answer}<br><small>${q.source}</small>`);}}}
 function answerChoice(b,q){if(locked)return;const ok=b.dataset.answer===q.a;if(q.book){bookStats[q.book].total++;if(ok)bookStats[q.book].correct++}b.classList.add(ok?"correct":"wrong");document.querySelectorAll("[data-answer]").forEach(x=>{x.disabled=true;if(x.dataset.answer===q.a)x.classList.add("correct")});finishAnswer(ok,`正确答案：${q.a}`)}
 function finishAnswer(ok,detail){locked=true;ok?correct++:wrong++;stats();const f=$("lit-feedback");f.className=`feedback ${ok?"correct-feedback":"wrong-feedback"}`;f.innerHTML=`<strong>${ok?"✓ 回答正确":"✕ 回答错误"}</strong><p>${detail}</p><button class="primary-button next-button" id="lit-next">${index===9?"查看结算":"下一题"}</button>`;f.hidden=false;$("lit-next").onclick=()=>{index++;index<10?showQuestion():finish()}}
 function showMatching(){const chosen=[];for(const item of shuffle(LiteratureData.matching)){if(chosen.some(x=>x.author===item.author||x.work===item.work))continue;chosen.push(item);if(chosen.length===6)break}items=chosen;pairs=[];selectedAuthor=null;$("lit-title").textContent="🔗 作者作品匹配";$("lit-round").textContent="6 组";$("lit-progress").style.width="0";$("lit-stats").innerHTML=`<div class="stat-item"><span>已配对</span><strong id="pair-count">0 / 6</strong></div><div class="stat-item"><span>操作</span><strong>先左后右</strong></div><div class="stat-item"><span>提交</span><strong>可重配</strong></div>`;$("lit-content").innerHTML=`<p class="matching-help">先点作者，再点作品。点击已配对项可取消后重新选择。</p><div class="matching-board"><div class="match-column" id="authors">${shuffle(chosen).map(x=>`<button data-author="${x.author}">${x.author}</button>`).join("")}</div><div class="match-column" id="works">${shuffle(chosen).map(x=>`<button data-work="${x.work}">${x.work}</button>`).join("")}</div></div><button class="primary-button match-submit" id="match-submit" disabled>提交全部配对</button>`;document.querySelectorAll("[data-author]").forEach(b=>b.onclick=()=>pickAuthor(b));document.querySelectorAll("[data-work]").forEach(b=>b.onclick=()=>pickWork(b));$("match-submit").onclick=submitMatches}
 function removePair(author){const p=pairs.find(x=>x.author===author);if(!p)return;pairs=pairs.filter(x=>x!==p);document.querySelector(`[data-author="${author}"]`).className="";document.querySelector(`[data-work="${p.work}"]`).className="";updatePairs()}
 function pickAuthor(b){if(b.classList.contains("paired")){removePair(b.dataset.author);return}document.querySelectorAll("[data-author]").forEach(x=>x.classList.remove("selected"));selectedAuthor=b.dataset.author;b.classList.add("selected")}
 function pickWork(b){if(b.classList.contains("paired")){const p=pairs.find(x=>x.work===b.dataset.work);removePair(p.author);return}if(!selectedAuthor)return;pairs.push({author:selectedAuthor,work:b.dataset.work});b.classList.add("paired");const a=document.querySelector(`[data-author="${selectedAuthor}"]`);a.classList.remove("selected");a.classList.add("paired");selectedAuthor=null;updatePairs()}
 function updatePairs(){$("pair-count").textContent=`${pairs.length} / 6`;$("match-submit").disabled=pairs.length!==6}
 function submitMatches(){correct=pairs.filter(p=>items.some(x=>x.author===p.author&&x.work===p.work)).length;wrong=6-correct;finish()}
 function finish(){const total=mode==="matching"?6:10,rate=Math.round(correct/total*100),score=correct*10,detail=mode!=="classics"?"":classicsMode==="综合挑战"?`<div class="book-result-grid">${BOOKS.map(book=>`<span>《${book}》<b>${bookStats[book].correct} / ${bookStats[book].total}</b></span>`).join("")}</div>`:`<p class="special-result-title">《${classicsMode}》专项挑战</p>`;$("lit-game").hidden=true;$("lit-result").innerHTML=`<div class="result-emoji">📖</div><p class="eyebrow">CHAPTER COMPLETE</p><h2>本局完成</h2><p class="score-line"><strong>${score}</strong><span>分</span></p><div class="result-grid"><div><small>正确</small><strong>${correct} / ${total}</strong></div><div><small>错误</small><strong>${wrong}</strong></div><div><small>正确率</small><strong>${rate}%</strong></div><div><small>本局得分</small><strong>${score}</strong></div></div>${detail}<div class="actions result-actions"><button class="primary-button" onclick="location.reload()">再玩一局</button><a class="text-button" href="./game-hall.html">返回游戏厅</a></div>`;$("lit-result").hidden=false}
})();
