(() => {
  const TOTAL = 5, $ = id => document.getElementById(id);
  let category = "random", questions = [], index = 0, xAnswer = null, xScore = 0, gScore = 0, xStreak = 0, gStreak = 0;
  function shuffle(items) { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
  function pickQuestions() { const pool = category === "random" ? lyricQuestions : lyricQuestions.filter(item => item.category === category); questions = shuffle(pool).slice(0, Math.min(TOTAL, pool.length)); }
  function reset(selectedCategory) { category = selectedCategory; index = xScore = gScore = xStreak = gStreak = 0; ["xs","gs","xst","gst"].forEach(id => { $(id).textContent = "0"; }); document.querySelectorAll("[data-category]").forEach(button => { button.classList.toggle("active", button.dataset.category === category); button.disabled = false; }); pickQuestions(); render(); }
  function render() { const q = questions[index]; xAnswer = null; $("round").textContent = `${index + 1} / ${questions.length}`; $("clue").innerHTML = `<small>${q.type}</small>${q.clue}`; $("g-entry").hidden = true; $("reveal").hidden = true; $("next").hidden = true; $("options").replaceChildren(); $("g-options").replaceChildren(); q.options.forEach((text, i) => { const button = document.createElement("button"); button.type = "button"; button.className = "arcade-option"; button.textContent = `${String.fromCharCode(65 + i)} · ${text}`; button.addEventListener("click", () => chooseX(i)); $("options").append(button); }); }
  function chooseX(i) { if (xAnswer !== null) return; xAnswer = i; document.querySelectorAll("[data-category]").forEach(button => { button.disabled = true; }); [...$("options").children].forEach((button, n) => { button.disabled = true; button.textContent = "🔒 小路的答案已隐藏"; if (n === i) button.classList.add("selected"); }); "ABCD".split("").forEach((letter, n) => { const button = document.createElement("button"); button.type = "button"; button.textContent = letter; button.setAttribute("aria-label", `录入小G答案 ${letter}`); button.addEventListener("click", () => reveal(n)); $("g-options").append(button); }); $("g-entry").hidden = false; }
  function reveal(gAnswer) { const q = questions[index], xc = xAnswer === q.answer, gc = gAnswer === q.answer; xScore += xc ? 1 : 0; gScore += gc ? 1 : 0; xStreak = xc ? xStreak + 1 : 0; gStreak = gc ? gStreak + 1 : 0; [...$("options").children].forEach((button, n) => { button.textContent = `${String.fromCharCode(65 + n)} · ${q.options[n]}`; button.classList.remove("selected"); if (n === q.answer) button.classList.add("correct"); if (n === xAnswer && !xc) button.classList.add("wrong"); }); [...$("g-options").children].forEach(button => { button.disabled = true; }); $("xs").textContent = xScore; $("gs").textContent = gScore; $("xst").textContent = xStreak; $("gst").textContent = gStreak; const label = n => `${String.fromCharCode(65 + n)} · ${q.options[n]}`; $("reveal").innerHTML = `<h2>${xc ? "小路答对" : "小路差一点"}，${gc ? "小G答对" : "小G差一点"}</h2><p>小路：<b>${label(xAnswer)}</b></p><p>小G：<b>${label(gAnswer)}</b></p><p>正确答案：<b>${label(q.answer)}</b></p><p class="song-meta">${q.song} · ${q.artist}</p>`; $("reveal").hidden = false; $("next").textContent = index === questions.length - 1 ? "查看结果 →" : "下一题 →"; $("next").hidden = false; $("g-entry").hidden = true; }
  function finish() { ArcadeStorage.addPlay("lyrics"); ArcadeStorage.saveLyricsResult(xScore, gScore, questions.length); $("play").hidden = true; const winner = xScore > gScore ? "小路获胜！" : xScore < gScore ? "小G获胜！" : "这一局平手！"; $("result").innerHTML = `<div class="result-emoji">🎶</div><p class="eyebrow">本局完成</p><h2>${winner}</h2><p>小路 ${xScore} : ${gScore} 小G</p><div class="actions result-actions"><button class="primary-button" onclick="location.reload()">再玩一局</button><a class="text-button" href="./game-hall.html">返回游戏厅</a></div>`; $("result").hidden = false; }
  $("next").addEventListener("click", () => { if (++index < questions.length) render(); else finish(); }); document.querySelectorAll("[data-category]").forEach(button => button.addEventListener("click", () => reset(button.dataset.category))); reset("random");
})();
