(() => {
  "use strict";
  const store=window.XiaoluNotesStore,loaded=store.load();let state=loaded.state,locked=Boolean(loaded.locked),activeNotebook="all";
  const $=selector=>document.querySelector(selector),noteDialog=$("#note-dialog"),noteForm=$("#note-form"),bookDialog=$("#notebook-dialog"),bookForm=$("#notebook-form"),moveDialog=$("#move-dialog"),moveForm=$("#move-form"),nowDate=new Date(),today=new Date(nowDate.getTime()-nowDate.getTimezoneOffset()*60000).toISOString().slice(0,10);
  const sourceNames={wish:"愿望",footprint:"足迹",memory:"回忆",exercise:"运动",gift:"礼物",achievement:"成就",project:"项目"},sourceRoutes={wish:["wishlist.html","wishId"],footprint:["footprints.html","placeId"],memory:["timeline.html","memoryId"],exercise:["exercise.html","recordId"],gift:["gifts.html","giftId"],achievement:["achievements.html",""]};
  if(loaded.warning){$("#storage-warning").hidden=false;$("#storage-warning").textContent=loaded.warning;}
  function persist(){if(locked)return false;const ok=store.save(state);if(!ok){$("#storage-warning").hidden=false;$("#storage-warning").textContent="浏览器存储空间不足，本次修改未保存。";}return ok;}
  let toastTimer;function notify(message){let toast=document.querySelector(".save-toast");if(!toast){toast=document.createElement("div");toast.className="save-toast";toast.setAttribute("role","status");document.body.append(toast)}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},2200)}
  function button(label,action,cls=""){const el=document.createElement("button");el.type="button";el.textContent=label;el.dataset.action=action;el.className=cls;return el;}
  function sourceHref(source){const route=sourceRoutes[source.module];return route?"./"+route[0]+(route[1]&&source.itemId?"?"+route[1]+"="+encodeURIComponent(source.itemId):""):"";}
  function memories(){return window.XiaoluTimelineStore?.load().state.memories||[]}
  function linkedMemory(note){return memories().find(memory=>memory.source.module==="note"&&memory.source.itemId===note.id||memory.links.noteIds?.includes(note.id))}
  function refreshNotebookSelects(){[$("#note-notebook"),$("#move-notebook")].forEach(select=>{const selected=select.value;select.replaceChildren(...state.notebooks.map(book=>Object.assign(document.createElement("option"),{value:book.id,textContent:`${book.emoji} ${book.name}`})));select.value=state.notebooks.some(book=>book.id===selected)?selected:"default"})}
  function notebookCard(book,count){const card=document.createElement("article");card.className="notebook-card"+(activeNotebook===book.id?" active":"");card.dataset.notebookId=book.id;card.style.setProperty("--notebook-color",book.coverColor);const choose=document.createElement("button");choose.type="button";choose.dataset.action="select-notebook";const emoji=document.createElement("span"),copy=document.createElement("span");emoji.className="notebook-emoji";emoji.textContent=book.emoji;copy.className="notebook-copy";copy.append(Object.assign(document.createElement("strong"),{textContent:book.name}),Object.assign(document.createElement("small"),{textContent:`${count} 篇`}));choose.append(emoji,copy);const tools=document.createElement("div");tools.className="notebook-actions";tools.append(button("编辑","edit-notebook"));if(book.id!=="default")tools.append(button("删除","delete-notebook","delete-action"));card.append(choose,tools);return card}
  function renderNotebooks(){const all=document.createElement("article");all.className="notebook-card all-notes"+(activeNotebook==="all"?" active":"");all.dataset.notebookId="all";const choose=document.createElement("button");choose.type="button";choose.dataset.action="select-notebook";choose.append(Object.assign(document.createElement("span"),{className:"notebook-emoji",textContent:"📚"}),Object.assign(document.createElement("span"),{className:"notebook-copy",innerHTML:`<strong>全部笔记</strong><small>${state.notes.length} 篇</small>`}));all.append(choose);$("#notebook-list").replaceChildren(all,...state.notebooks.map(book=>notebookCard(book,state.notes.filter(note=>note.notebookId===book.id).length)));refreshNotebookSelects()}
  function updateTags(){const select=$("#tag-filter"),selected=select.value,tags=[...new Set(state.notes.flatMap(note=>note.tags))].sort((a,b)=>a.localeCompare(b,"zh-CN"));select.replaceChildren(Object.assign(document.createElement("option"),{value:"",textContent:"全部标签"}),...tags.map(value=>Object.assign(document.createElement("option"),{value,textContent:"# "+value})));select.value=tags.includes(selected)?selected:""}
  function card(item){const el=document.createElement("article");el.className="record-card note-card";el.dataset.id=item.id;const book=state.notebooks.find(value=>value.id===item.notebookId)||state.notebooks.find(value=>value.id==="default");const top=document.createElement("div"),h=document.createElement("h3"),badge=document.createElement("span");top.className="record-top";h.textContent=item.title;badge.className="notebook-badge";badge.style.setProperty("--notebook-color",book?.coverColor||"#fff0e8");badge.textContent=`${book?.emoji||"📥"} ${book?.name||"默认笔记"}`;top.append(h,badge);el.append(top);const meta=document.createElement("div");meta.className="record-meta";meta.append(Object.assign(document.createElement("span"),{textContent:item.date}));if(item.source.module!=="manual"){meta.append(Object.assign(document.createElement("span"),{textContent:"来自"+(sourceNames[item.source.module]||"关联模块")+(item.source.label?" · "+item.source.label:"")}));const href=sourceHref(item.source);if(href){const link=document.createElement("a");link.href=href;link.textContent="查看来源 →";meta.append(link)}}el.append(meta);const body=document.createElement("p");body.textContent=item.body;el.append(body);if(item.tags.length){const tags=document.createElement("div");tags.className="tag-row";item.tags.forEach(value=>{const tag=document.createElement("button");tag.type="button";tag.className="tag";tag.dataset.tag=value;tag.textContent="# "+value;tags.append(tag)});el.append(tags)}const actions=document.createElement("div");actions.className="record-actions";const linked=linkedMemory(item),memoryLink=document.createElement("a");if(linked){memoryLink.href="./timeline.html?memoryId="+encodeURIComponent(linked.id);memoryLink.textContent="查看关联回忆"}else{const params=new URLSearchParams({source:"note",sourceId:item.id,sourceLabel:item.title,title:item.title,body:item.body,date:item.date,tags:item.tags.join("，")});memoryLink.href="./timeline.html?"+params;memoryLink.textContent="写成回忆"}actions.append(memoryLink,button("移动","move"),button("编辑","edit"),button("删除","delete","delete-action"));el.append(actions);return el}
  function render(){renderNotebooks();updateTags();const q=$("#note-search").value.trim().toLowerCase(),tag=$("#tag-filter").value;const rows=state.notes.filter(note=>(activeNotebook==="all"||note.notebookId===activeNotebook)&&(!tag||note.tags.includes(tag))&&(!q||(note.title+" "+note.body+" "+note.tags.join(" ")).toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));const current=activeNotebook==="all"?"全部笔记":state.notebooks.find(book=>book.id===activeNotebook)?.name||"笔记";$("#result-summary").textContent=`${current} · ${rows.length} 篇`;if(rows.length)$("#note-list").replaceChildren(...rows.map(card));else{const el=document.createElement("div"),icon=document.createElement("span"),text=document.createElement("p");el.className="empty-state";icon.textContent="✍️";text.textContent="这里还没有符合条件的小纸条。";el.append(icon,text);$("#note-list").replaceChildren(el)}}
  function openNote(item=null,prefill={}){noteForm.reset();const source=item?.source||prefill.source||{module:"manual",itemId:"",label:""};$("#note-id").value=item?.id||"";$("#note-date").value=item?.date||prefill.date||today;$("#note-notebook").value=item?.notebookId||(activeNotebook!=="all"?activeNotebook:"default");$("#note-title").value=item?.title||prefill.title||"";$("#note-body").value=item?.body||prefill.body||"";$("#note-tags").value=(item?.tags||prefill.tags||[]).join("，");$("#note-source-module").value=source.module||"manual";$("#note-source-id").value=source.itemId||"";$("#note-source-label").value=source.label||"";$("#dialog-title").textContent=item?"编辑笔记":"新建笔记";noteDialog.showModal()}
  function openNotebook(book=null){bookForm.reset();$("#notebook-id").value=book?.id||"";$("#notebook-name").value=book?.name||"";$("#notebook-emoji").value=book?.emoji||"📓";$("#notebook-color").value=book?.coverColor||"#fff0e8";$("#notebook-dialog-title").textContent=book?"编辑笔记本":"新建笔记本";updateNotebookPreview();bookDialog.showModal()}
  function updateNotebookPreview(){const name=$("#notebook-name").value.trim()||"新笔记本",emoji=$("#notebook-emoji").value.trim()||"📓",color=$("#notebook-color").value;$("#notebook-preview-name").textContent=name;$("#notebook-preview-emoji").textContent=emoji;$("#notebook-preview").style.background=color}
  function openMove(note){$("#move-note-id").value=note.id;$("#move-note-title").textContent=`“${note.title}”现在位于 ${state.notebooks.find(book=>book.id===note.notebookId)?.name||"默认笔记"}`;$("#move-notebook").value=note.notebookId;moveDialog.showModal()}
  function highlight(id){requestAnimationFrame(()=>{const found=document.querySelector('.record-card[data-id="'+CSS.escape(id)+'"]');if(found){found.classList.add("source-highlight");found.scrollIntoView({block:"center"})}})}
  $("#add-note").addEventListener("click",()=>openNote());$("#add-notebook").addEventListener("click",()=>openNotebook());document.querySelectorAll(".dialog-close,.cancel-button").forEach(control=>control.addEventListener("click",()=>control.closest("dialog").close()));document.querySelectorAll("dialog").forEach(element=>element.addEventListener("click",event=>{if(event.target===element)element.close()}));
  noteForm.addEventListener("submit",event=>{event.preventDefault();if(locked)return;const now=new Date().toISOString(),current=state.notes.find(note=>note.id===$("#note-id").value),raw={id:$("#note-id").value,date:$("#note-date").value,notebookId:$("#note-notebook").value,category:current?.category||"其他",title:$("#note-title").value,body:$("#note-body").value,tags:$("#note-tags").value,source:{module:$("#note-source-module").value,itemId:$("#note-source-id").value,label:$("#note-source-label").value},updatedAt:now},next=store.normalizeNote({...current,...raw,createdAt:current?.createdAt||now});if(current)Object.assign(current,next);else state.notes.push(next);if(persist()){noteDialog.close();render();highlight(next.id);notify(current?"笔记已更新":"笔记已保存")}});
  bookForm.addEventListener("submit",event=>{event.preventDefault();if(locked)return;const current=state.notebooks.find(book=>book.id===$("#notebook-id").value),now=new Date().toISOString(),next=store.normalizeNotebook({...current,id:current?.id,name:$("#notebook-name").value,emoji:$("#notebook-emoji").value,coverColor:$("#notebook-color").value,builtIn:current?.builtIn||false,createdAt:current?.createdAt||now,updatedAt:now});if(current)Object.assign(current,next);else state.notebooks.push(next);if(persist()){bookDialog.close();render();notify(current?"笔记本已更新":"笔记本已创建")}});["notebook-name","notebook-emoji","notebook-color"].forEach(id=>$("#"+id).addEventListener("input",updateNotebookPreview));
  moveForm.addEventListener("submit",event=>{event.preventDefault();if(locked)return;const note=state.notes.find(item=>item.id===$("#move-note-id").value);if(!note)return;note.notebookId=$("#move-notebook").value;note.updatedAt=new Date().toISOString();if(persist()){moveDialog.close();render();notify("笔记已移动")}});
  $("#notebook-list").addEventListener("click",event=>{const action=event.target.closest("[data-action]"),card=event.target.closest("[data-notebook-id]");if(!action||!card)return;const id=card.dataset.notebookId,book=state.notebooks.find(value=>value.id===id);if(action.dataset.action==="select-notebook"){activeNotebook=id;render()}else if(action.dataset.action==="edit-notebook"&&book)openNotebook(book);else if(action.dataset.action==="delete-notebook"&&book){if(state.notes.some(note=>note.notebookId===book.id)){notify("请先移动笔记，非空笔记本不能删除");return}if(confirm(`确定删除空笔记本“${book.name}”吗？`)){state.notebooks=state.notebooks.filter(value=>value.id!==book.id);if(activeNotebook===book.id)activeNotebook="all";if(persist()){render();notify("空笔记本已删除")}}}});
  $("#note-list").addEventListener("click",event=>{const tag=event.target.closest("[data-tag]");if(tag){$("#tag-filter").value=tag.dataset.tag;render();return}const action=event.target.closest("[data-action]");if(!action)return;const item=state.notes.find(note=>note.id===action.closest(".record-card")?.dataset.id);if(!item)return;if(action.dataset.action==="edit")openNote(item);else if(action.dataset.action==="move")openMove(item);else if(action.dataset.action==="delete"&&confirm("确定删除这篇笔记吗？不会删除关联的回忆。")){state.notes=state.notes.filter(note=>note.id!==item.id);if(persist()){render();notify("笔记已删除")}}});
  $("#note-search").addEventListener("input",render);$("#tag-filter").addEventListener("change",render);
  const params=new URLSearchParams(location.search),source=params.get("source");render();if(params.get("noteId"))highlight(params.get("noteId"));else if(store.SOURCE_MODULES.includes(source)&&source!=="manual")openNote(null,{date:params.get("date")||today,title:params.get("title")||"",body:params.get("body")||"",source:{module:source,itemId:params.get("sourceId")||"",label:params.get("sourceLabel")||""}});
})();
