(() => {
  "use strict";
  const store=window.XiaoluNotesStore,loaded=store.load();let state=loaded.state,locked=Boolean(loaded.locked);
  const $=s=>document.querySelector(s),dialog=$("#note-dialog"),form=$("#note-form"),nowDate=new Date(),today=new Date(nowDate.getTime()-nowDate.getTimezoneOffset()*60000).toISOString().slice(0,10);
  const sourceNames={wish:"愿望",footprint:"足迹",memory:"回忆",exercise:"运动"},sourceRoutes={wish:["wishlist.html","wishId"],footprint:["footprints.html","placeId"],memory:["timeline.html","memoryId"],exercise:["exercise.html","recordId"]};
  if(loaded.warning){$("#storage-warning").hidden=false;$("#storage-warning").textContent=loaded.warning;}store.CATEGORIES.forEach(category=>[$("#category-filter"),$("#note-category")].forEach(select=>{const option=document.createElement("option");option.value=category;option.textContent=category;select.append(option)}));
  function persist(){if(locked)return false;const ok=store.save(state);if(!ok){$("#storage-warning").hidden=false;$("#storage-warning").textContent="浏览器存储空间不足，本次修改未保存。";}return ok;}
  let toastTimer;function notify(message){let toast=document.querySelector(".save-toast");if(!toast){toast=document.createElement("div");toast.className="save-toast";toast.setAttribute("role","status");document.body.append(toast)}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},2200)}
  function button(label,action,cls=""){const el=document.createElement("button");el.type="button";el.textContent=label;el.dataset.action=action;el.className=cls;return el;}
  function sourceHref(source){const route=sourceRoutes[source.module];return route&&source.itemId?"./"+route[0]+"?"+route[1]+"="+encodeURIComponent(source.itemId):"";}
  function card(item){const el=document.createElement("article");el.className="record-card";el.dataset.id=item.id;const top=document.createElement("div"),h=document.createElement("h3"),cat=document.createElement("span");top.className="record-top";h.textContent=item.title;cat.className="tag";cat.textContent=item.category;top.append(h,cat);el.append(top);const meta=document.createElement("div");meta.className="record-meta";const date=document.createElement("span");date.textContent=item.date;meta.append(date);if(item.source.module!=="manual"){const source=document.createElement("span");source.textContent="来自"+(sourceNames[item.source.module]||"关联模块")+(item.source.label?" · "+item.source.label:"");meta.append(source);const href=sourceHref(item.source);if(href){const link=document.createElement("a");link.href=href;link.textContent="查看来源 →";meta.append(link)}}el.append(meta);const body=document.createElement("p");body.textContent=item.body;el.append(body);if(item.tags.length){const tags=document.createElement("div");tags.className="tag-row";item.tags.forEach(value=>{const x=document.createElement("span");x.className="tag";x.textContent="# "+value;tags.append(x)});el.append(tags)}const actions=document.createElement("div");actions.className="record-actions";const memory=document.createElement("a"),params=new URLSearchParams({source:"note",sourceId:item.id,sourceLabel:item.title,title:item.title,body:item.body,date:item.date});memory.href="./timeline.html?"+params;memory.textContent="写成回忆";actions.append(memory,button("编辑","edit"),button("删除","delete","delete-action"));el.append(actions);return el;}
  function render(){const q=$("#note-search").value.trim().toLowerCase(),category=$("#category-filter").value,tag=$("#tag-filter").value.trim().toLowerCase();const rows=state.notes.filter(x=>(!category||x.category===category)&&(!tag||x.tags.some(t=>t.toLowerCase().includes(tag)))&&(!q||(x.title+" "+x.body+" "+x.tags.join(" ")).toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));$("#result-summary").textContent=(state.notebooks[0]?.name||"笔记")+" · "+rows.length+" 条";if(rows.length)$("#note-list").replaceChildren(...rows.map(card));else{const el=document.createElement("div"),i=document.createElement("span"),p=document.createElement("p");el.className="empty-state";i.textContent="✍️";p.textContent="这里还没有符合条件的小纸条。";el.append(i,p);$("#note-list").replaceChildren(el);}}
  function open(item=null,prefill={}){form.reset();const source=item?.source||prefill.source||{module:"manual",itemId:"",label:""};$("#note-id").value=item?.id||"";$("#note-date").value=item?.date||today;$("#note-category").value=item?.category||"其他";$("#note-title").value=item?.title||prefill.title||"";$("#note-body").value=item?.body||"";$("#note-tags").value=(item?.tags||[]).join("，");$("#note-source-module").value=source.module||"manual";$("#note-source-id").value=source.itemId||"";$("#note-source-label").value=source.label||"";$("#dialog-title").textContent=item?"编辑笔记":"新建笔记";dialog.showModal();}
  function highlight(id){requestAnimationFrame(()=>{const card=document.querySelector('.record-card[data-id="'+CSS.escape(id)+'"]');if(card){card.classList.add("source-highlight");card.scrollIntoView({block:"center"});}})}
  $("#add-note").addEventListener("click",()=>open());document.querySelectorAll(".dialog-close,.cancel-button").forEach(x=>x.addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
  form.addEventListener("submit",e=>{e.preventDefault();if(locked)return;const now=new Date().toISOString(),raw={id:$("#note-id").value,date:$("#note-date").value,category:$("#note-category").value,title:$("#note-title").value,body:$("#note-body").value,tags:$("#note-tags").value,notebookId:"default",source:{module:$("#note-source-module").value,itemId:$("#note-source-id").value,label:$("#note-source-label").value},updatedAt:now};const current=state.notes.find(x=>x.id===raw.id),next=store.normalizeNote({...current,...raw,createdAt:current?.createdAt||now});if(current)Object.assign(current,next);else state.notes.push(next);if(persist()){dialog.close();render();highlight(next.id);notify(current?"笔记已更新":"笔记已保存");}});
  $("#note-list").addEventListener("click",e=>{const action=e.target.closest("[data-action]");if(!action)return;const item=state.notes.find(x=>x.id===action.closest(".record-card")?.dataset.id);if(!item)return;if(action.dataset.action==="edit")open(item);if(action.dataset.action==="delete"&&confirm("确定删除这篇笔记吗？不会删除关联的来源记录。")){state.notes=state.notes.filter(x=>x.id!==item.id);if(persist()){render();notify("笔记已删除")}}});
  ["note-search","tag-filter"].forEach(id=>$("#"+id).addEventListener("input",render));$("#category-filter").addEventListener("change",render);
  const params=new URLSearchParams(location.search),source=params.get("source");render();if(params.get("noteId"))highlight(params.get("noteId"));else if(store.SOURCE_MODULES.includes(source)&&source!=="manual")open(null,{title:params.get("title")||"",source:{module:source,itemId:params.get("sourceId")||"",label:params.get("sourceLabel")||""}});
})();
