(() => { "use strict";
 const store=window.XiaoluNotesStore,loaded=store.load();let state=loaded.state,locked=Boolean(loaded.locked);const $=s=>document.querySelector(s),dialog=$("#note-dialog"),form=$("#note-form"),nowDate=new Date(),today=new Date(nowDate.getTime()-nowDate.getTimezoneOffset()*60000).toISOString().slice(0,10);
 if(loaded.warning){$("#storage-warning").hidden=false;$("#storage-warning").textContent=loaded.warning;}store.CATEGORIES.forEach(category=>[$("#category-filter"),$("#note-category")].forEach(select=>{const option=document.createElement("option");option.value=category;option.textContent=category;select.append(option)}));
 function persist(){if(locked)return false;const ok=store.save(state);if(!ok){$("#storage-warning").hidden=false;$("#storage-warning").textContent="浏览器存储空间不足，本次修改未保存。";}return ok;}
 function button(label,action,cls=""){const el=document.createElement("button");el.type="button";el.textContent=label;el.dataset.action=action;el.className=cls;return el;}
 function card(item){const el=document.createElement("article");el.className="record-card";el.dataset.id=item.id;const top=document.createElement("div"),h=document.createElement("h3"),cat=document.createElement("span");top.className="record-top";h.textContent=item.title;cat.className="tag";cat.textContent=item.category;top.append(h,cat);el.append(top);const meta=document.createElement("div");meta.className="record-meta";meta.textContent=item.date;el.append(meta);const body=document.createElement("p");body.textContent=item.body;el.append(body);if(item.tags.length){const tags=document.createElement("div");tags.className="tag-row";item.tags.forEach(value=>{const x=document.createElement("span");x.className="tag";x.textContent=`# ${value}`;tags.append(x)});el.append(tags)}const actions=document.createElement("div");actions.className="record-actions";actions.append(button("编辑","edit"),button("删除","delete","delete-action"));el.append(actions);return el;}
 function render(){const q=$("#note-search").value.trim().toLowerCase(),category=$("#category-filter").value,tag=$("#tag-filter").value.trim().toLowerCase();const rows=state.notes.filter(x=>(!category||x.category===category)&&(!tag||x.tags.some(t=>t.toLowerCase().includes(tag)))&&(!q||`${x.title} ${x.body} ${x.tags.join(" ")}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));$("#result-summary").textContent=`${state.notebooks[0]?.name||"笔记"} · ${rows.length} 条`;if(rows.length)$("#note-list").replaceChildren(...rows.map(card));else{const el=document.createElement("div"),i=document.createElement("span"),p=document.createElement("p");el.className="empty-state";i.textContent="✍️";p.textContent="这里还没有符合条件的小纸条。";el.append(i,p);$("#note-list").replaceChildren(el);}}
 function open(item=null){form.reset();$("#note-id").value=item?.id||"";$("#note-date").value=item?.date||today;$("#note-category").value=item?.category||"其他";$("#note-title").value=item?.title||"";$("#note-body").value=item?.body||"";$("#note-tags").value=(item?.tags||[]).join("，");$("#dialog-title").textContent=item?"编辑笔记":"新建笔记";dialog.showModal();}
 $("#add-note").addEventListener("click",()=>open());document.querySelectorAll(".dialog-close,.cancel-button").forEach(x=>x.addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});form.addEventListener("submit",e=>{e.preventDefault();if(locked)return;const now=new Date().toISOString(),raw={id:$("#note-id").value,date:$("#note-date").value,category:$("#note-category").value,title:$("#note-title").value,body:$("#note-body").value,tags:$("#note-tags").value,notebookId:"default",updatedAt:now};const current=state.notes.find(x=>x.id===raw.id),next=store.normalizeNote({...current,...raw,createdAt:current?.createdAt||now});if(current)Object.assign(current,next);else state.notes.push(next);if(persist()){dialog.close();render();}});$("#note-list").addEventListener("click",e=>{const action=e.target.closest("[data-action]");if(!action)return;const item=state.notes.find(x=>x.id===action.closest(".record-card")?.dataset.id);if(!item)return;if(action.dataset.action==="edit")open(item);if(action.dataset.action==="delete"&&confirm("确定删除这篇笔记吗？")){state.notes=state.notes.filter(x=>x.id!==item.id);if(persist())render();}});["note-search","tag-filter"].forEach(id=>$("#"+id).addEventListener("input",render));$("#category-filter").addEventListener("change",render);render();
})();
