(() => {
 const $=id=>document.getElementById(id),KEY="xiaoluXiaogPiMemoryV1";let mode,timerId,remaining;
 const read=()=>{try{return {...{freeBest:0,timedBest:0},...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{freeBest:0,timedBest:0}}};
 function record(){const r=read();$("pi-record").textContent=`历史最佳：自由 ${r.freeBest} 位 · 60 秒 ${r.timedBest} 位`}
 document.querySelectorAll("[data-pi-mode]").forEach(b=>b.onclick=()=>start(b.dataset.piMode));
 function start(m){mode=m;$("pi-setup").hidden=true;$("pi-game").hidden=false;$("pi-mode-title").textContent=m==="free"?"π = 3. 自由背诵":"π = 3. 60 秒挑战";$("pi-input").value="";$("pi-input").focus();if(m==="timed"){remaining=60;paintTimer();timerId=setInterval(()=>{remaining--;paintTimer();if(remaining<=0)submit()},1000)}else $("pi-timer").textContent="不限时"}
 function paintTimer(){$("pi-timer").textContent=`${remaining} 秒`}
 function submit(){clearInterval(timerId);const raw=$("pi-input").value,user=raw.replace(/\D/g,"").slice(0,PiDigits.length);let score=0;while(score<user.length&&user[score]===PiDigits[score])score++;const wrongAt=score<user.length?score+1:null,r=read(),k=mode==="free"?"freeBest":"timedBest";r[k]=Math.max(r[k],score);localStorage.setItem(KEY,JSON.stringify(r));$("pi-game").hidden=true;const max=Math.max(user.length,Math.min(score+10,PiDigits.length)),correctAnswer=PiDigits.slice(0,max);$("pi-result").innerHTML=`<div class="result-emoji">🥧</div><p class="eyebrow">PI RESULT</p><h2>本次成绩：${score} 位</h2><p>${wrongAt?`第 ${wrongAt} 位开始出错`:(user.length?"输入的数字全部正确":"还没有输入数字")}</p><div class="pi-compare"><div><small>用户输入</small><code>${mark(user,wrongAt)}</code></div><div><small>正确答案</small><code>${mark(correctAnswer,wrongAt)}</code></div><div><small>第一次错误位置</small><strong>${wrongAt?`小数点后第 ${wrongAt} 位`:"无"}</strong></div></div><p class="record-line">本模式历史最高：${r[k]} 位</p><div class="actions result-actions"><button class="primary-button" onclick="location.reload()">再来一次</button><a class="text-button" href="./game-hall.html">返回游戏厅</a></div>`;$("pi-result").hidden=false}
 function mark(s,pos){const esc=s.replace(/[&<>]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[x]));return pos?`${esc.slice(0,pos-1)}<mark>${esc[pos-1]||"∅"}</mark>${esc.slice(pos)}`:esc||"（未输入）"}
 $("pi-input").oninput=e=>{const clean=e.target.value.replace(/[^0-9\s]/g,"");if(clean!==e.target.value)e.target.value=clean};$("pi-submit").onclick=submit;$("pi-cancel").onclick=()=>location.reload();record();
})();
