(() => {
  const $ = id => document.getElementById(id), shuffle = list => { const copy = [...list]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
  let total, questions, index, score, streak, maxStreak, locked;
  function showRecord() { const b = ArcadeStorage.read().provinceBest || {}; $("province-record").textContent = `历史最佳：10题 ${b.ten || 0} 分 · 20题 ${b.twenty || 0} 分 · 最高连胜 ${b.streak || 0}`; }
  function start(count) { total = count; questions = shuffle(ProvinceQuestions).slice(0, total); index = score = streak = maxStreak = 0; $("province-setup").hidden = true; $("province-game").hidden = false; const grid = $("province-grid"); grid.innerHTML = ProvinceNames.map(name => `<button data-province="${name}">${name}</button>`).join(""); grid.querySelectorAll("button").forEach(b => b.addEventListener("click", choose)); showQuestion(); }
  function showQuestion() { locked = false; $("province-round").textContent = `题目 ${index + 1} / ${total}`; $("province-city").textContent = questions[index].city; $("province-feedback").textContent = ""; document.querySelectorAll("#province-grid button").forEach(b => { b.disabled = false; b.className = ""; }); updateStats(); }
  function updateStats() { $("province-score").textContent = score; $("province-streak").textContent = streak; $("province-max").textContent = maxStreak; }
  function choose(event) { if (locked) return; locked = true; const selected = event.currentTarget.dataset.province, correctProvince = questions[index].province, correct = selected === correctProvince; document.querySelectorAll("#province-grid button").forEach(b => { b.disabled = true; if (b.dataset.province === correctProvince) b.classList.add("correct"); }); if (correct) { score++; streak++; maxStreak = Math.max(maxStreak, streak); $("province-feedback").textContent = `答对了！${questions[index].city}属于${correctProvince}`; } else { streak = 0; event.currentTarget.classList.add("wrong"); $("province-feedback").textContent = `正确答案：${correctProvince}`; } updateStats(); setTimeout(() => { index++; index < total ? showQuestion() : finish(); }, 800); }
  function finish() { ArcadeStorage.addPlay("province"); const best = ArcadeStorage.saveProvinceBest(total, score, maxStreak), accuracy = Math.round(score / total * 100); $("province-game").hidden = true; const result = $("province-result"); result.innerHTML = `<div class="result-emoji">🗺️</div><p class="eyebrow">CHALLENGE COMPLETE</p><h2>${score} / ${total}</h2><div class="result-details"><span>正确率 ${accuracy}%</span><span>最高连胜 ${maxStreak}</span><span>历史最佳 ${total === 20 ? best.twenty : best.ten} 分</span></div><div class="actions result-actions"><button class="primary-button" onclick="location.reload()">再玩一局</button><a class="text-button" href="./game-hall.html">返回游戏厅</a></div>`; result.hidden = false; }
  document.querySelectorAll("[data-total]").forEach(b => b.addEventListener("click", () => start(Number(b.dataset.total)))); showRecord();
})();
