(() => {
 const $=id=>document.getElementById(id),KEY="xiaoluXiaogSpeedQuizV1",shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};let qs,index,score,correct,wrong,timeouts,combo,maxCombo,times,correctTimes,startAt,raf,locked;
 const read=()=>{try{return {...{highScore:0,maxCombo:0,fastestCorrect:null},...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{highScore:0,maxCombo:0,fastestCorrect:null}}},wait=ms=>new Promise(r=>setTimeout(r,ms));
 function record(){const r=read();$("speed-record").textContent=`历史最高 ${r.highScore} 分 · 最高连击 ×${r.maxCombo} · 最快正确 ${r.fastestCorrect==null?"--":r.fastestCorrect.toFixed(2)+" 秒"}`}
 $("speed-start").onclick=async()=>{$("speed-setup").hidden=true;$("speed-countdown").hidden=false;for(const v of ["3","2","1","GO！"]){$("countdown-value").textContent=v;await wait(v==="GO！"?650:750)}$("speed-countdown").hidden=true;start()};
 function start(){qs=shuffle(SpeedQuizData).slice(0,20);index=score=correct=wrong=timeouts=combo=maxCombo=0;times=[];correctTimes=[];$("speed-game").hidden=false;show()}
 function show(){locked=false;const q=qs[index];$("speed-round").textContent=`${index+1} / 20`;$("speed-combo").textContent=`连击 ×${combo}`;$("speed-score").textContent=`${score} 分`;$("speed-category").textContent=q.c;$("speed-question").textContent=q.q;$("speed-options").innerHTML=shuffle(q.o).map(x=>`<button data-speed-answer="${x}">${x}</button>`).join("");$("speed-feedback").hidden=true;document.querySelectorAll("[data-speed-answer]").forEach(b=>b.onclick=()=>answer(b));startAt=performance.now();tick()}
 function tick(){const elapsed=(performance.now()-startAt)/1000,left=Math.max(0,10-elapsed);$("speed-seconds").textContent=left.toFixed(1);$("speed-timer-bar").style.width=`${left*10}%`;$("speed-timer-bar").classList.toggle("danger",left<=3);if(left<=0){timeout();return}raf=requestAnimationFrame(tick)}
 function answer(b){if(locked)return;locked=true;cancelAnimationFrame(raf);const elapsed=Math.min(10,(performance.now()-startAt)/1000),ok=b.dataset.speedAnswer===qs[index].a;times.push(elapsed);document.querySelectorAll("[data-speed-answer]").forEach(x=>{x.disabled=true;if(x.dataset.speedAnswer===qs[index].a)x.classList.add("correct")});if(ok){combo++;maxCombo=Math.max(maxCombo,combo);correct++;correctTimes.push(elapsed);const gained=100+Math.floor(Math.max(0,10-elapsed))*10+combo*10;score+=gained;b.classList.add("correct");flash(`✓ 正确 +${gained}`,true)}else{wrong++;combo=0;b.classList.add("wrong");flash("✕ 错误",false)}advance()}
 function timeout(){if(locked)return;locked=true;cancelAnimationFrame(raf);timeouts++;combo=0;times.push(10);document.querySelectorAll("[data-speed-answer]").forEach(x=>{x.disabled=true;if(x.dataset.speedAnswer===qs[index].a)x.classList.add("correct")});flash("TIME OUT！",false);advance()}
 function flash(text,ok){const f=$("speed-feedback");f.textContent=text;f.className=`speed-feedback ${ok?"ok":"bad"}`;f.hidden=false;$("speed-combo").textContent=`连击 ×${combo}`;$("speed-score").textContent=`${score} 分`}
 function advance(){setTimeout(()=>{index++;index<20?show():finish()},650)}
 function finish(){const avg=times.reduce((a,b)=>a+b,0)/20,fast=correctTimes.length?Math.min(...correctTimes):null,rate=Math.round(correct/20*100),r=read();r.highScore=Math.max(r.highScore,score);r.maxCombo=Math.max(r.maxCombo,maxCombo);if(fast!=null)r.fastestCorrect=r.fastestCorrect==null?fast:Math.min(r.fastestCorrect,fast);localStorage.setItem(KEY,JSON.stringify(r));$("speed-game").hidden=true;$("speed-result").innerHTML=`<div class="result-emoji">⚡</div><p class="eyebrow">SPEED REPORT</p><h2>⚡ 本局战绩</h2><p class="score-line"><strong>${score}</strong><span>分</span></p><div class="speed-result-list"><span>正确 <b>${correct} / 20</b></span><span>错误 <b>${wrong}</b></span><span>超时 <b>${timeouts}</b></span><span>正确率 <b>${rate}%</b></span><span>最高连击 <b>×${maxCombo}</b></span><span>平均答题时间 <b>${avg.toFixed(2)} 秒</b></span><span>最快正确答题 <b>${fast==null?"--":fast.toFixed(2)+" 秒"}</b></span><span>总得分 <b>${score}</b></span></div><p class="record-line">历史最高 ${r.highScore} 分 · 最高连击 ×${r.maxCombo} · 最快正确 ${r.fastestCorrect==null?"--":r.fastestCorrect.toFixed(2)+" 秒"}</p><div class="actions result-actions"><button class="primary-button" onclick="location.reload()">再来一局</button><a class="text-button" href="./game-hall.html">返回游戏厅</a></div>`;$("speed-result").hidden=false}
 record();
})();
