(function(){
"use strict";
const KEY="xiaoluXiaogVocabularyV2",VERSION=3,DAILY=50,MANIFEST="./data/wordbooks/manifest.json",$=id=>document.getElementById(id),object=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
let manifest=[],words=[],byId=new Map(),active=null,warning="",storageLocked=false,state=loadRoot();
function blankRoot(){return{version:VERSION,selectedBookId:"kaoyan-required",books:{}}}
function loadRoot(){try{const raw=localStorage.getItem(KEY);if(!raw)return blankRoot();const v=JSON.parse(raw);return v?.version===VERSION?{version:VERSION,selectedBookId:v.selectedBookId||"kaoyan-required",books:object(v.books)}:blankRoot()}catch(e){storageLocked=true;warning="浏览器中的学习数据无法读取，已使用安全的空白状态；原数据没有被覆盖。";console.warn(e);return blankRoot()}}
function save(){if(storageLocked)return false;try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){warning="这次进度无法写入浏览器，请先导出备份并检查存储空间。";console.warn(e);return false}}
function emptyBook(m){return{bookId:m.bookId,name:m.name,source:m.source,totalWords:m.totalWords,currentPosition:0,learnedCount:0,learned:{},skipped:{},wrong:{},history:[],session:null}}
const meta=()=>manifest.find(x=>x.bookId===state.selectedBookId),book=()=>state.books[state.selectedBookId],validId=id=>manifest.some(x=>x.bookId===id);
function normalizeBook(value,m){const i=object(value),s=emptyBook(m);s.currentPosition=Number.isInteger(i.currentPosition)?Math.max(0,Math.min(i.currentPosition,m.totalWords)):0;s.learned=object(i.learned);s.learnedCount=Object.keys(s.learned).length;s.skipped=object(i.skipped);s.wrong=object(i.wrong);s.history=Array.isArray(i.history)?i.history.filter(x=>x&&typeof x.date==="string").slice(0,366):[];if(i.session&&["daily","review"].includes(i.session.mode)&&Array.isArray(i.session.queue)){s.session={mode:i.session.mode,queue:i.session.queue.filter(id=>byId.has(id)),round:i.session.round===1?1:0,index:Math.max(0,Number(i.session.index)||0),correct:Number(i.session.correct)||0,wrong:Number(i.session.wrong)||0,skipped:Number(i.session.skipped)||0,startedAt:i.session.startedAt||new Date().toISOString(),scanCursor:Number.isInteger(i.session.scanCursor)?i.session.scanCursor:s.currentPosition}}return s}
async function loadBook(id){const chosen=manifest.find(x=>x.bookId===id)||manifest[0],response=await fetch(chosen.file);if(!response.ok)throw Error(`词书读取失败：${response.status}`);const payload=await response.json();if(payload.bookId!==chosen.bookId||!Array.isArray(payload.words))throw Error("词书格式不正确");words=payload.words.filter(x=>x&&typeof x.id==="string"&&typeof x.word==="string"&&typeof x.meaning==="string");byId=new Map(words.map(x=>[x.id,x]));state.selectedBookId=chosen.bookId;state.books[chosen.bookId]=normalizeBook(state.books[chosen.bookId],chosen);save();renderDashboard()}
async function init(){try{const response=await fetch(MANIFEST);if(!response.ok)throw Error(`词书清单读取失败：${response.status}`);manifest=await response.json();if(!Array.isArray(manifest)||manifest.length<4)throw Error("词书清单不完整");if(!validId(state.selectedBookId))state.selectedBookId=manifest[0].bookId;$("book-select").innerHTML=manifest.map(x=>`<option value="${x.bookId}">${x.name}（${x.totalWords.toLocaleString()} 词）</option>`).join("");await loadBook(state.selectedBookId)}catch(e){$("daily-range").textContent=e.message;$("start-button").disabled=true;console.error(e)}}
function eligibleFrom(start,count,excluded=[]){const out=[],no=new Set(excluded),data=book();let i=start;while(i<words.length&&out.length<count){const w=words[i++];if(!data.skipped[w.id]&&!no.has(w.id))out.push(w.id)}return{ids:out,next:i}}
function nextPlan(){return eligibleFrom(book().currentPosition,DAILY).ids.map(id=>byId.get(id))}
function newSession(mode){const data=book(),found=mode==="daily"?eligibleFrom(data.currentPosition,DAILY):{ids:Object.keys(data.wrong).filter(id=>byId.has(id)&&!data.skipped[id]),next:data.currentPosition};return found.ids.length?{mode,queue:found.ids,round:0,index:0,correct:0,wrong:0,skipped:0,startedAt:new Date().toISOString(),scanCursor:found.next}:null}
const current=()=>active&&byId.get(active.queue[active.index]),format=w=>`${w.word}${w.phonetic?` ${w.phonetic}`:""}`;
function achievements(d){const days=new Set(d.history.map(x=>x.date.slice(0,10))).size;return[{icon:"🌱",name:"第一次学习",on:d.history.length>0},{icon:"📚",name:"学会 50 词",on:d.learnedCount>=50},{icon:"🔥",name:"坚持 7 天",on:days>=7},{icon:"✨",name:"清空错词",on:d.history.some(x=>x.mode==="review")&&!Object.keys(d.wrong).length}]}
function renderDashboard(){if(!manifest.length)return;active=null;const d=book(),m=meta(),wrong=Object.keys(d.wrong).filter(id=>byId.has(id)).length;$("dashboard").hidden=false;$("session").hidden=true;$("result").hidden=true;$("book-select").value=m.bookId;$("book-source").textContent=`${m.totalWords.toLocaleString()} 词 · ${m.license} · 数据来自 ECDICT 派生词库`;$("learned-count").textContent=d.learnedCount;$("wrong-count").textContent=wrong;$("review-badge").textContent=wrong;$("day-count").textContent=new Set(d.history.map(x=>x.date.slice(0,10))).size;const plan=nextPlan();$("daily-range").textContent=plan.length?`${format(plan[0])} → ${format(plan.at(-1))}（${plan.length} 词）`:`《${m.name}》已全部走完，可以继续复习错词。`;$("start-button").disabled=!plan.length;$("review-button").disabled=!wrong;$("resume-banner").hidden=!d.session;if(d.session)$("resume-copy").textContent=`《${m.name}》· ${d.session.mode==="daily"?"每日学习":"错词复习"} · 第 ${d.session.round+1} 轮 · ${Math.min(d.session.index+1,d.session.queue.length)} / ${d.session.queue.length}`;$("achievement-list").innerHTML=achievements(d).map(x=>`<span class="study-achievement ${x.on?"unlocked":""}"><b>${x.icon}</b>${x.name}</span>`).join("");if(warning)$("daily-range").textContent=warning+" "+$("daily-range").textContent}
function begin(session){active=session;if(!active)return;storageLocked=false;book().session=active;save();$("dashboard").hidden=true;$("result").hidden=true;$("session").hidden=false;showWord()}
function showWord(){const w=current();if(!w){completeRound();return}const en=active.round===0;$("round-label").textContent=`${active.mode==="review"?"错词复习":"今日 50 词"} · 第 ${active.round+1} 轮`;$("direction-label").textContent=en?"第一轮：英 → 中":"第二轮：中 → 英";$("session-progress-text").textContent=`${active.index+1} / ${active.queue.length}`;$("session-progress-bar").style.width=`${active.queue.length?active.index/active.queue.length*100:0}%`;$("unit-label").textContent=meta().name;$("prompt-label").textContent=en?"看到英文，说出中文":"看到中文，说出英文";$("word-prompt").textContent=en?format(w):w.meaning;$("answer-text").textContent=en?w.meaning:format(w);$("answer-panel").hidden=true;$("reveal-button").hidden=false;$("skip-button").hidden=active.round!==0}
function rate(kind){const w=current(),d=book();if(!w)return;if(kind==="skip"&&active.round===0){d.skipped[w.id]={at:new Date().toISOString(),word:w.word};delete d.wrong[w.id];delete d.learned[w.id];active.skipped++;active.queue.splice(active.index,1);if(active.mode==="daily"){const fill=eligibleFrom(active.scanCursor,1,active.queue);if(fill.ids.length){active.queue.push(fill.ids[0]);active.scanCursor=fill.next}}if(active.index>=active.queue.length){completeRound();return}}else{if(kind==="wrong"){active.wrong++;const old=d.wrong[w.id]||{count:0},direction=active.round===0?"en-zh":"zh-en";d.wrong[w.id]={count:(old.count||0)+1,lastWrongAt:new Date().toISOString(),directions:{...object(old.directions),[direction]:(object(old.directions)[direction]||0)+1}}}else{active.correct++;if(active.mode==="review")delete d.wrong[w.id]}if(active.mode==="daily")d.learned[w.id]={lastSeenAt:new Date().toISOString()};active.index++}d.learnedCount=Object.keys(d.learned).length;d.session=active;save();showWord()}
function completeRound(){if(active.round===0&&active.queue.length){active.round=1;active.index=0;book().session=active;save();showWord();return}finish()}
function finish(){const d=book();if(active.mode==="daily")d.currentPosition=Math.max(d.currentPosition,active.scanCursor);d.learnedCount=Object.keys(d.learned).length;d.history.unshift({date:new Date().toISOString(),mode:active.mode,words:active.queue.length,correct:active.correct,wrong:active.wrong,skipped:active.skipped});d.history=d.history.slice(0,366);d.session=null;save();$("session").hidden=true;$("result").hidden=false;$("result-title").textContent=active.mode==="daily"?"今天的两轮完成啦":"错词复习完成啦";$("result-copy").textContent=active.mode==="daily"?"英→中和中→英都走过一遍，下次继续按当前词书顺序前进。":"答对的词已经移出这本词书的错词本。";$("result-stats").innerHTML=`<span><strong>${active.queue.length}</strong> 个词</span><span><strong>${active.correct}</strong> 次记住</span><span><strong>${active.wrong}</strong> 次没记住</span><span><strong>${active.skipped}</strong> 个跳过</span>`;active=null}
function renderHistory(){const d=book();$("history-list").innerHTML=d.history.length?d.history.map(x=>`<article class="history-entry"><strong>${x.mode==="daily"?"每日学习":"错词复习"} · ${new Date(x.date).toLocaleString("zh-CN")}</strong><small>${x.words} 词 · 记住 ${x.correct} 次 · 没记住 ${x.wrong} 次 · 跳过 ${x.skipped||0}</small></article>`).join(""):'<p class="empty-message">这本词书还没有学习记录。</p>'}
function exportData(){const blob=new Blob([JSON.stringify({app:"xiaolu-xiaog-vocabulary",schemaVersion:VERSION,exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`一起背单词-${new Date().toLocaleDateString("sv-SE")}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$("data-message").textContent="四本词书的学习数据已导出。"}
async function importData(file){try{if(!file||file.size>5*1024*1024)throw Error("文件为空或超过 5 MB");const p=JSON.parse(await file.text());if(p.app!=="xiaolu-xiaog-vocabulary"||p.schemaVersion!==VERSION||p.data?.version!==VERSION)throw Error("不是可识别的多词书 v2.0 备份");storageLocked=false;state={version:VERSION,selectedBookId:validId(p.data.selectedBookId)?p.data.selectedBookId:manifest[0].bookId,books:object(p.data.books)};await loadBook(state.selectedBookId);$("data-message").textContent="导入成功，所有词书进度已恢复。"}catch(e){$("data-message").textContent=`导入失败：${e.message}`}}
$("book-select").onchange=async e=>{if(book()?.session&&!confirm("当前词书有未完成进度。切换后仍会保留，确定切换吗？")){e.target.value=state.selectedBookId;return}await loadBook(e.target.value)};$("start-button").onclick=()=>begin(newSession("daily"));$("review-button").onclick=()=>begin(newSession("review"));$("resume-button").onclick=()=>begin(book().session);$("reveal-button").onclick=()=>{$("reveal-button").hidden=true;$("answer-panel").hidden=false};$("wrong-button").onclick=()=>rate("wrong");$("skip-button").onclick=()=>rate("skip");$("correct-button").onclick=()=>rate("correct");$("exit-button").onclick=renderDashboard;$("result-home").onclick=renderDashboard;$("history-button").onclick=()=>{renderHistory();$("history-dialog").showModal()};$("data-button").onclick=()=>{$("data-message").textContent="";$("data-dialog").showModal()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());$("export-button").onclick=exportData;$("import-input").onchange=e=>importData(e.target.files[0]);
window.StudyApp={loadBook,newSession,eligibleFrom,getState:()=>state,getBook:book,getWords:()=>words,rate};init();
})();
