(() => {
  const $ = id => document.getElementById(id);
  let round = 1, running = false, startAt = 0, target = 10, lastActionAt = -Infinity;
  const results = [];
  const format = value => `${value.toFixed(2)} 秒`;
  function showRecords() { const best = ArcadeStorage.read().timerSoloBest || {}; const single = Number.isFinite(best.single) ? format(best.single) : "暂无"; const average = Number.isFinite(best.average) ? format(best.average) : "暂无"; $("records").textContent = `历史最佳单次误差：${single} · 历史最佳平均误差：${average}`; }
  function rating(average) { if (average <= .15) return "时间魔法师 🪄"; if (average <= .30) return "人体秒表 ⏱️"; if (average <= .60) return "时间感很好 ✨"; if (average <= 1) return "差一点点 🌙"; return "时间去哪了 🌀"; }
  function renderRounds() { $("round-results").innerHTML = results.map((item, index) => `<div><small>第 ${index + 1} 回合 · 目标 ${format(item.target)}</small><strong>实际 ${format(item.actual)}</strong><span>误差 ${format(item.error)}</span></div>`).join(""); }
  function start() { running = true; startAt = performance.now(); $("timer-button").textContent = "停止"; $("timer-button").classList.add("is-running"); $("turn").textContent = "计时中…"; $("hint").textContent = `目标 ${format(target)}，现在看不到时间哦`; document.querySelectorAll('input[name="target"]').forEach(input => { input.disabled = true; }); }
  function stop() { const actual = (performance.now() - startAt) / 1000; const error = Math.abs(actual - target); running = false; results.push({ target, actual, error }); renderRounds(); $("timer-button").classList.remove("is-running"); $("hint").textContent = `目标 ${format(target)} · 实际 ${format(actual)} · 误差 ${format(error)}`; if (round < 3) { round += 1; $("round").textContent = `第 ${round} / 3 回合`; $("turn").textContent = "下一回合"; $("timer-button").textContent = "开始"; document.querySelectorAll('input[name="target"]').forEach(input => { input.disabled = false; }); } else finish(); }
  function finish() { ArcadeStorage.addPlay("timer"); const average = results.reduce((sum, item) => sum + item.error, 0) / results.length; const bestSingle = Math.min(...results.map(item => item.error)); const best = ArcadeStorage.saveTimerSolo(results.map(item => item.error)); $("play").hidden = true; $("result").innerHTML = `<div class="result-emoji">⏱️</div><p class="eyebrow">三回合完成</p><h2>${rating(average)}</h2><div class="result-details timer-summary"><span>平均误差 <b>${format(average)}</b></span><span>最佳单次 <b>${format(bestSingle)}</b></span><span>历史最佳平均 <b>${format(best.average)}</b></span></div><div class="actions result-actions"><button class="primary-button" onclick="location.reload()">再玩一局</button><a class="text-button" href="./game-hall.html">返回游戏厅</a></div>`; $("result").hidden = false; }
  document.querySelectorAll('input[name="target"]').forEach(input => input.addEventListener("change", () => { target = Number(input.value); }));
  $("timer-button").addEventListener("click", () => { const now = performance.now(); if (now - lastActionAt < 350) return; lastActionAt = now; running ? stop() : start(); }); showRecords();
})();
