(() => {
  "use strict";
  const store=window.XiaoluTimelineStore,loaded=store.load();let state=loaded.state,locked=Boolean(loaded.locked),view="all";
  const $=s=>document.querySelector(s),dialog=$("#memory-dialog"),form=$("#memory-form"),nowDate=new Date(),today=new Date(nowDate.getTime()-nowDate.getTimezoneOffset()*60000).toISOString().slice(0,10);
  const sourceNames={manual:"手动记录",wish:"来自愿望",footprint:"来自足迹",exercise:"来自运动",note:"来自笔记",achievement:"来自成就",gift:"来自礼物",project:"来自项目"};
  const sourceRoutes={wish:["wishlist.html","wishId"],footprint:["footprints.html","placeId"],exercise:["exercise.html","recordId"],note:["notes.html","noteId"],gift:["gifts.html","giftId"],achievement:["achievements.html",""]};
  if(loaded.warning){$("#storage-warning").hidden=false;$("#storage-warning").textContent=loaded.warning;}
  function persist(){if(locked)return false;const ok=store.save(state);if(!ok){$("#storage-warning").hidden=false;$("#storage-warning").textContent="浏览器存储空间不足，本次修改未保存。";}return ok;}
  let toastTimer;function notify(message){let toast=document.querySelector(".save-toast");if(!toast){toast=document.createElement("div");toast.className="save-toast";toast.setAttribute("role","status");document.body.append(toast)}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},2200)}
  function button(label,action,cls=""){const el=document.createElement("button");el.type="button";el.textContent=label;el.dataset.action=action;el.className=cls;return el;}
  function itemHref(module,itemId){const route=sourceRoutes[module];if(!route)return "";return "./"+route[0]+(route[1]&&itemId?"?"+route[1]+"="+encodeURIComponent(itemId):"");}
  function dateLabel(value){const parsed=new Date(`${value}T00:00:00`);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(parsed);}
  function linkBack(memory){
    const source=memory.source;if(!source?.itemId)return;
    if(source.module==="note"&&window.XiaoluNotesStore){const notes=window.XiaoluNotesStore.load();if(!notes.locked&&notes.state.notes.some(item=>item.id===source.itemId))window.XiaoluNotesStore.save(window.XiaoluNotesStore.linkMemory(notes.state,source.itemId,memory.id));}
    if(source.module==="gift"&&window.XiaoluGiftsStore){const gifts=window.XiaoluGiftsStore.load();if(!gifts.locked&&gifts.state.gifts.some(item=>item.id===source.itemId))window.XiaoluGiftsStore.save(window.XiaoluGiftsStore.linkMemory(gifts.state,source.itemId,memory.id));}
  }
  function unlinkBack(memoryId){
    if(window.XiaoluNotesStore){const notes=window.XiaoluNotesStore.load();if(!notes.locked&&notes.state.notes.some(item=>item.links.memoryIds.includes(memoryId)))window.XiaoluNotesStore.save(window.XiaoluNotesStore.unlinkMemory(notes.state,memoryId));}
    if(window.XiaoluGiftsStore){const gifts=window.XiaoluGiftsStore.load();if(!gifts.locked&&gifts.state.gifts.some(item=>item.links.memoryIds.includes(memoryId)))window.XiaoluGiftsStore.save(window.XiaoluGiftsStore.unlinkMemory(gifts.state,memoryId));}
  }
  function relatedLinks(item){const wrap=document.createElement("div");wrap.className="relation-row";Object.entries(store.LINK_FIELDS).forEach(([module,field])=>{const ids=item.links[field]||[];if(!ids.length)return;const href=itemHref(module,ids[0]),label=(sourceNames[module]||module).replace("来自","");const el=href?document.createElement("a"):document.createElement("span");if(href)el.href=href;el.textContent=`${label} · ${ids.length}`;wrap.append(el)});return wrap;}
  function card(item){
    const el=document.createElement("article");el.className="record-card memory-card"+(item.pinned?" is-pinned":"")+(item.favorite?" is-favorite":"");el.dataset.id=item.id;
    const top=document.createElement("div"),h=document.createElement("h3"),marks=document.createElement("div");top.className="record-top";h.textContent=item.title;marks.className="memory-marks";if(item.pinned){const pin=document.createElement("span");pin.textContent="📌 置顶";marks.append(pin)}if(item.favorite){const star=document.createElement("span");star.textContent="⭐ 收藏";marks.append(star)}top.append(h,marks);el.append(top);
    const meta=document.createElement("div");meta.className="record-meta";[item.place?"📍 "+item.place:"",sourceNames[item.source.module],item.source.label].filter(Boolean).forEach(value=>{const span=document.createElement("span");span.textContent=value;meta.append(span)});const sourceHref=itemHref(item.source.module,item.source.itemId);if(sourceHref&&item.source.itemId){const link=document.createElement("a");link.href=sourceHref;link.textContent="查看来源 →";meta.append(link)}el.append(meta);
    const body=document.createElement("p");body.textContent=item.body;el.append(body);
    if(item.tags.length){const tags=document.createElement("div");tags.className="tag-row";item.tags.forEach(value=>{const tag=document.createElement("button");tag.type="button";tag.className="tag";tag.dataset.tag=value;tag.textContent="# "+value;tags.append(tag)});el.append(tags)}
    const relations=relatedLinks(item);if(relations.children.length)el.append(relations);
    if(item.imageRef){const link=document.createElement("a");link.className="memory-image-link";link.href=item.imageRef;link.target="_blank";link.rel="noopener noreferrer";link.textContent="查看照片引用 ↗";el.append(link)}
    const actions=document.createElement("div");actions.className="record-actions";const noteLink=document.createElement("a"),params=new URLSearchParams({source:"memory",sourceId:item.id,sourceLabel:item.title,title:item.title});noteLink.href="./notes.html?"+params;noteLink.textContent="写小纸条";actions.append(button(item.pinned?"取消置顶":"置顶", "pin"),button(item.favorite?"取消收藏":"收藏","favorite"),noteLink,button("编辑","edit"),button("删除","delete","delete-action"));el.append(actions);return el;
  }
  function group(title,items,pinned=false){const section=document.createElement("section");section.className="memory-date-group"+(pinned?" pinned-group":"");const heading=document.createElement("h2");heading.textContent=title;section.append(heading,...items.map(card));return section;}
  function empty(){const el=document.createElement("div");el.className="empty-state";const icon=document.createElement("span"),text=document.createElement("p");icon.textContent=view==="pinned"?"📌":view==="favorite"?"⭐":"📖";text.textContent=view==="all"?"时间线还是空白，写下第一条想珍藏的回忆吧。":"这里还没有符合当前筛选的回忆。";el.append(icon,text);return el;}
  function updateTags(){const select=$("#tag-filter"),selected=select.value,tags=[...new Set(state.memories.flatMap(item=>item.tags))].sort((a,b)=>a.localeCompare(b,"zh-CN"));select.replaceChildren(Object.assign(document.createElement("option"),{value:"",textContent:"全部标签"}),...tags.map(value=>Object.assign(document.createElement("option"),{value,textContent:"# "+value})));select.value=tags.includes(selected)?selected:"";}
  function render(){
    updateTags();const q=$("#memory-search").value.trim().toLowerCase(),source=$("#source-filter").value,tag=$("#tag-filter").value;
    const rows=state.memories.filter(item=>(view==="all"||view==="pinned"&&item.pinned||view==="favorite"&&item.favorite)&&(!source||item.source.module===source)&&(!tag||item.tags.includes(tag))&&(!q||(item.title+" "+item.body+" "+item.place+" "+item.tags.join(" ")).toLowerCase().includes(q))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));
    $("#result-summary").textContent=`共 ${rows.length} 条回忆${rows.some(item=>item.pinned)?` · ${rows.filter(item=>item.pinned).length} 条置顶`:""}`;
    if(!rows.length){$("#timeline-list").replaceChildren(empty());return}
    const sections=[],pinned=rows.filter(item=>item.pinned),normal=rows.filter(item=>!item.pinned);if(pinned.length)sections.push(group("📌 置顶回忆",pinned,true));
    const dates=[...new Set(normal.map(item=>item.date))];dates.forEach(date=>sections.push(group(dateLabel(date),normal.filter(item=>item.date===date))));$("#timeline-list").replaceChildren(...sections);
  }
  function open(item=null,prefill={}){form.reset();const source=item?.source||prefill.source||{module:"manual",itemId:"",label:""};$("#memory-id").value=item?.id||"";$("#memory-date").value=item?.date||prefill.date||today;$("#memory-title").value=item?.title||prefill.title||"";$("#memory-body").value=item?.body||prefill.body||"";$("#memory-place").value=item?.place||prefill.place||"";$("#memory-tags").value=(item?.tags||prefill.tags||[]).join("，");$("#memory-image").value=item?.imageRef||prefill.imageRef||"";$("#memory-favorite").checked=Boolean(item?.favorite);$("#memory-pinned").checked=Boolean(item?.pinned);$("#source-module").value=source.module||"manual";$("#source-id").value=source.itemId||"";$("#source-label").value=source.label||"";$("#dialog-title").textContent=item?"编辑这条回忆":"写一条回忆";dialog.showModal();}
  function highlight(id){requestAnimationFrame(()=>{const found=document.querySelector('.record-card[data-id="'+CSS.escape(id)+'"]');if(found){found.classList.add("source-highlight");found.scrollIntoView({block:"center"})}})}
  $("#add-memory").addEventListener("click",()=>open());document.querySelectorAll(".dialog-close,.cancel-button").forEach(element=>element.addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});
  form.addEventListener("submit",event=>{event.preventDefault();if(locked)return;const now=new Date().toISOString(),raw={id:$("#memory-id").value,date:$("#memory-date").value,title:$("#memory-title").value,body:$("#memory-body").value,place:$("#memory-place").value,tags:$("#memory-tags").value,imageRef:$("#memory-image").value,favorite:$("#memory-favorite").checked,pinned:$("#memory-pinned").checked,source:{module:$("#source-module").value||"manual",itemId:$("#source-id").value,label:$("#source-label").value},updatedAt:now};const current=state.memories.find(item=>item.id===raw.id),next=store.normalizeMemory({...current,...raw,createdAt:current?.createdAt||now});if(current)Object.assign(current,next);else state.memories.push(next);if(persist()){linkBack(next);dialog.close();render();highlight(next.id);notify(current?"回忆已更新":"回忆已保存")}});
  $("#timeline-list").addEventListener("click",event=>{const tag=event.target.closest("[data-tag]");if(tag){$("#tag-filter").value=tag.dataset.tag;render();return}const action=event.target.closest("[data-action]");if(!action)return;const item=state.memories.find(record=>record.id===action.closest(".record-card")?.dataset.id);if(!item)return;if(action.dataset.action==="edit")open(item);else if(action.dataset.action==="pin"){item.pinned=!item.pinned;item.updatedAt=new Date().toISOString();if(persist()){render();notify(item.pinned?"回忆已置顶":"已取消置顶")}}else if(action.dataset.action==="favorite"){item.favorite=!item.favorite;item.updatedAt=new Date().toISOString();if(persist()){render();notify(item.favorite?"已收藏这条回忆":"已取消收藏")}}else if(action.dataset.action==="delete"&&confirm("确定删除这条回忆吗？不会删除它关联的来源记录。")){state.memories=state.memories.filter(record=>record.id!==item.id);if(persist()){unlinkBack(item.id);render();notify("回忆已删除")}}});
  document.querySelectorAll("[data-memory-filter]").forEach(control=>control.addEventListener("click",()=>{view=control.dataset.memoryFilter;document.querySelectorAll("[data-memory-filter]").forEach(button=>{const active=button===control;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});render()}));
  $("#memory-search").addEventListener("input",render);$("#source-filter").addEventListener("change",render);$("#tag-filter").addEventListener("change",render);
  const params=new URLSearchParams(location.search),source=store.SOURCE_ALIASES[params.get("source")]||params.get("source"),sourceId=params.get("sourceId")||"",targetId=params.get("memoryId")||"";
  render();if(targetId)highlight(targetId);else if(store.SOURCE_MODULES.includes(source)&&source!=="manual"){
    const field=store.LINK_FIELDS[source],existing=state.memories.find(item=>sourceId&&(item.source.module===source&&item.source.itemId===sourceId||field&&item.links[field]?.includes(sourceId)));
    if(existing)highlight(existing.id);else open(null,{date:params.get("date")||today,title:params.get("title")||"",body:params.get("body")||"",place:params.get("place")||"",imageRef:params.get("imageRef")||"",tags:(params.get("tags")||"").split(/[，,]/).filter(Boolean),source:{module:source,itemId:sourceId,label:params.get("sourceLabel")||""}});
  }
})();
