let round=1,player="xiaolu",running=false,startAt=0,target=10,lastActionAt=-Infinity;const errors={xiaolu:[],xiaog:[]};const $=id=>document.getElementById(id);
function showRecords(){const b=ArcadeStorage.read().timerBest;$("records").textContent=`历史最佳误差：小路 ${b.xiaolu===null?"暂无":b.xiaolu.toFixed(2)+" 秒"} · 小G ${b.xiaog===null?"暂无":b.xiaog.toFixed(2)+" 秒"}`;}showRecords();
document.querySelectorAll('input[name="target"]').forEach(r=>r.onchange=()=>{target=Number(r.value);});
$("timer-button").onclick=()=>{const now=performance.now();if(now-lastActionAt<350)return;lastActionAt=now;running?stop():start();};
function start(){running=true;startAt=performance.now();$("timer-button").textContent="停止";$("hint").textContent=`目标 ${target.toFixed(2)} 秒，跟着感觉走……`;document.querySelectorAll('input[name="target"]').forEach(r=>r.disabled=true);}
function stop(){const actual=(performance.now()-startAt)/1000,error=Math.abs(actual-target);running=false;errors[player].push(error);ArcadeStorage.saveTimerBest(player,error);const who=player==="xiaolu"?"小路":"小G";$(player==="xiaolu"?"xr":"gr").innerHTML=`<span>实际：${actual.toFixed(2)} 秒</span><small>误差：${error.toFixed(2)} 秒</small>`;$("hint").textContent=`${who}停在 ${actual.toFixed(2)} 秒，距离 ${target.toFixed(2)} 秒只差 ${error.toFixed(2)} 秒！`;showRecords();
  if(player==="xiaolu"){player="xiaog";$("turn").textContent="小G回合";$("timer-button").textContent="帮小G开始";}else if(round<3){round++;player="xiaolu";$("round").textContent=`第 ${round} / 3 回合`;$("turn").textContent="小路回合";$("timer-button").textContent="开始下一回合";$("xr").textContent="等待";$("gr").textContent="等待";}else{finish();}}
function avg(list){return list.reduce((a,b)=>a+b,0)/list.length;}
function finish(){ArcadeStorage.addPlay("timer");const x=avg(errors.xiaolu),g=avg(errors.xiaog),winner=Math.abs(x-g)<.0005?"这一局平手！":x<g?"小路获胜！":"小G获胜！";$("play").hidden=true;$("result").innerHTML=`<div class="result-emoji">⏱️</div><p class="eyebrow">三回合完成</p><h2>${winner}</h2><p>小路平均误差：<b>${x.toFixed(2)} 秒</b><br>小G平均误差：<b>${g.toFixed(2)} 秒</b></p><div class="actions" style="justify-content:center"><button class="primary-button" onclick="location.reload()">再玩一局</button><a class="text-button" href="game-hall.html">返回游戏厅</a></div>`;$("result").hidden=false;}
