(() => {
  "use strict";
  const store=window.XiaoluTimelineStore,loaded=store.load();
  let state=loaded.state,locked=Boolean(loaded.locked);
  const $=s=>document.querySelector(s),dialog=$("#memory-dialog"),form=$("#memory-form"),nowDate=new Date(),today=new Date(nowDate.getTime()-nowDate.getTimezoneOffset()*60000).toISOString().slice(0,10);
  const sourceNames={manual:"手动记录",wish:"来自愿望",footprint:"来自足迹",exercise:"来自运动",note:"来自笔记",achievement:"来自成就",gift:"来自礼物",project:"来自项目"};
  const sourceRoutes={wish:["wishlist.html","wishId"],footprint:["footprints.html","placeId"],exercise:["exercise.html","recordId"],note:["notes.html","noteId"]};
  [["gift","礼物"],["project","项目"]].forEach(([value,label])=>{[$("#source-filter"),$("#source-module")].forEach(select=>{const option=document.createElement("option");option.value=value;option.textContent=label;select.append(option)})});
  if(loaded.warning){$("#storage-warning").hidden=false;$("#storage-warning").textContent=loaded.warning;}
  function persist(){if(locked)return false;const ok=store.save(state);if(!ok){$("#storage-warning").hidden=false;$("#storage-warning").textContent="浏览器存储空间不足，本次修改未保存。";}return ok;}
  let toastTimer;function notify(message){let toast=document.querySelector(".save-toast");if(!toast){toast=document.createElement("div");toast.className="save-toast";toast.setAttribute("role","status");document.body.append(toast)}toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},2200)}
  function button(label,action,cls=""){const el=document.createElement("button");el.type="button";el.textContent=label;el.dataset.action=action;el.className=cls;return el;}
  function sourceHref(source){const route=sourceRoutes[source.module];return route&&source.itemId?"./"+route[0]+"?"+route[1]+"="+encodeURIComponent(source.itemId):"";}
  function card(item){
    const el=document.createElement("article");el.className="record-card";el.dataset.id=item.id;
    const top=document.createElement("div"),h=document.createElement("h3"),date=document.createElement("span");top.className="record-top";h.textContent=item.title;date.className="tag";date.textContent=item.date;top.append(h,date);el.append(top);
    const meta=document.createElement("div");meta.className="record-meta";[item.place?"📍 "+item.place:"",sourceNames[item.source.module],item.source.label].filter(Boolean).forEach(x=>{const span=document.createElement("span");span.textContent=x;meta.append(span)});
    const href=sourceHref(item.source);if(href){const link=document.createElement("a");link.href=href;link.textContent="查看来源 →";meta.append(link)}el.append(meta);
    const body=document.createElement("p");body.textContent=item.body;el.append(body);
    if(item.tags.length){const tags=document.createElement("div");tags.className="tag-row";item.tags.forEach(value=>{const x=document.createElement("span");x.className="tag";x.textContent="# "+value;tags.append(x)});el.append(tags)}
    if(item.imageRef){const link=document.createElement("a");link.className="memory-image-link";link.href=item.imageRef;link.target="_blank";link.rel="noopener noreferrer";link.textContent="查看照片引用 ↗";el.append(link)}
    const actions=document.createElement("div");actions.className="record-actions";const noteLink=document.createElement("a"),params=new URLSearchParams({source:"memory",sourceId:item.id,sourceLabel:item.title,title:item.title});noteLink.href="./notes.html?"+params;noteLink.textContent="写小纸条";actions.append(noteLink,button("编辑","edit"),button("删除","delete","delete-action"));el.append(actions);return el;
  }
  function empty(){const el=document.createElement("div");el.className="empty-state";const i=document.createElement("span"),p=document.createElement("p");i.textContent="📖";p.textContent="时间线还是空白，写下第一条想珍藏的回忆吧。";el.append(i,p);return el;}
  function render(){const q=$("#memory-search").value.trim().toLowerCase(),source=$("#source-filter").value,tag=$("#tag-filter").value.trim().toLowerCase();const rows=state.memories.filter(x=>(!source||x.source.module===source)&&(!tag||x.tags.some(t=>t.toLowerCase().includes(tag)))&&(!q||(x.title+" "+x.body+" "+x.place+" "+x.tags.join(" ")).toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));$("#result-summary").textContent="共 "+rows.length+" 条回忆";$("#timeline-list").replaceChildren(...(rows.length?rows.map(card):[empty()]));}
  function open(item=null,prefill={}){form.reset();const source=item?.source||prefill.source||{module:"manual",itemId:"",label:""};$("#memory-id").value=item?.id||"";$("#memory-date").value=item?.date||prefill.date||today;$("#memory-title").value=item?.title||prefill.title||"";$("#memory-body").value=item?.body||prefill.body||"";$("#memory-place").value=item?.place||prefill.place||"";$("#memory-tags").value=(item?.tags||[]).join("，");$("#memory-image").value=item?.imageRef||"";$("#source-module").value=source.module||"manual";$("#source-id").value=source.itemId||"";$("#source-label").value=source.label||"";$("#dialog-title").textContent=item?"编辑这条回忆":"写一条回忆";dialog.showModal();}
  function highlight(id){requestAnimationFrame(()=>{const card=document.querySelector('.record-card[data-id="'+CSS.escape(id)+'"]');if(card){card.classList.add("source-highlight");card.scrollIntoView({block:"center"});}})}
  $("#add-memory").addEventListener("click",()=>open());document.querySelectorAll(".dialog-close,.cancel-button").forEach(x=>x.addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
  form.addEventListener("submit",e=>{e.preventDefault();if(locked)return;const now=new Date().toISOString(),raw={id:$("#memory-id").value,date:$("#memory-date").value,title:$("#memory-title").value,body:$("#memory-body").value,place:$("#memory-place").value,tags:$("#memory-tags").value,imageRef:$("#memory-image").value,source:{module:$("#source-module").value||"manual",itemId:$("#source-id").value,label:$("#source-label").value},updatedAt:now};const current=state.memories.find(x=>x.id===raw.id),next=store.normalizeMemory({...current,...raw,createdAt:current?.createdAt||now});if(current)Object.assign(current,next);else state.memories.push(next);if(persist()){dialog.close();render();highlight(next.id);notify(current?"回忆已更新":"回忆已保存");}});
  $("#timeline-list").addEventListener("click",e=>{const action=e.target.closest("[data-action]");if(!action)return;const item=state.memories.find(x=>x.id===action.closest(".record-card")?.dataset.id);if(!item)return;if(action.dataset.action==="edit")open(item);if(action.dataset.action==="delete"&&confirm("确定删除这条回忆吗？不会删除它关联的来源记录。")){state.memories=state.memories.filter(x=>x.id!==item.id);if(persist()){render();notify("回忆已删除")}}});
  ["memory-search","tag-filter"].forEach(id=>$("#"+id).addEventListener("input",render));$("#source-filter").addEventListener("change",render);
  const params=new URLSearchParams(location.search),aliases={wishlist:"wish",footprints:"footprint",notes:"note"},source=aliases[params.get("source")]||params.get("source"),sourceId=params.get("sourceId")||"",targetId=params.get("memoryId")||"";
  render();if(targetId)highlight(targetId);else if(store.SOURCE_MODULES.includes(source)&&source!=="manual"){const existing=source==="wish"&&state.memories.find(x=>x.source.module==="wish"&&x.source.itemId===sourceId);if(existing)highlight(existing.id);else open(null,{date:params.get("date")||today,title:params.get("title")||"",body:params.get("body")||"",place:params.get("place")||"",source:{module:source,itemId:sourceId,label:params.get("sourceLabel")||""}});}
})();
